### ISSUE TITLE
ios project.pbxproj refers to .mm files rather than .m files

### ISSUE THREAD

**Issue by lastarrats** [callstack/react-native-builder-bob#101]
Creating a package choosing Kotlin and Objective-C, project.pbxproj refers to .mm files instead .m files

Run:
npx @react-native-community/bob create react-native-awesome-module

? What type of package do you want to develop? 
❯ Native module in Kotlin and Objective-C 

cd ios/AwesomeModule.xcodeproj 
vi project.pbxproj 

-- All references refer to AwesomeModule.mm rather than AwesomeModule.m

**Comment by cainaleaouk** [comment]
@lastarrats Doing a find and replace on `project.pbxproj` to fix the file extensions worked for me 👍
