### ISSUE TITLE
Sample packages published with Kotlin

### ISSUE THREAD

**Issue by sajaddp** [callstack/react-native-builder-bob#103]
Hi
The official react-native document does not tutorial to build a Kotlin-based package, can you please mention some packages that were written with react-native-builder-bob's help and are now at npm?

**Comment by alpha0010** [comment]
I recently created https://github.com/alpha0010/react-native-pdf-viewer .  Uses Kotlin (Swift for iOS) and has both a native module and a native UI component.

No claims that my code is good.  However it is small, so perhaps easier to learn from.

**Comment by troZee** [comment]
@sajaddp you can just copy and paste java code and android studio will transform it into kotlin language easily. 

Or you can just checkout my PR https://github.com/callstack/react-native-builder-bob/pull/105

**Comment by BartoszKlonowski** [comment]
Hello @sajaddp!
I can see that a couple of months after your question there has been a Kotlin + Swift support added to the *react-native-builder-bob*.
Can you please check if #129 solves your issue?
