### ISSUE TITLE
Error installing bob-created module into existing RN application (iOS build phase)

### ISSUE THREAD

**Issue by shorsher** [callstack/react-native-builder-bob#113]
## Ask your Question
I'm having trouble installing a native module I created (kotlin & objective c) into an existing RN app.  The example application within my module works great, but an `npm install <my module>` seems to break building the iOS (only version I can test currently) build of my application with the error:

```
error Unable to resolve module `<my module name>` from `src/services/<myfile>.ts`: <my module name> could not be found within the project.
```

`npm install` finishes and import/autocomplete/type definitions of my module within my editor are working fine. From within Xcode, I can also see my native pod in `Pods>Development pods`. I have tried both resetting my metro cache and cleaning my iOS build folder. 

I also attempted to install the barebones bob project with the multiply example in my application and run into the same error.

Install flow:
In module I created:
1. ```npm run prepare```

In RN application:
1. `npm install <local path to my module>`. Note: I am installing as a local package during development
2. `cd ios && pod install`
3. Attempt to build onto my iPhone via Xcode

react-native info:
```
(node:38521) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 1.50 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /var/folders/dj/fvcdsjcn3_s0g6cxb5kcq2wr0000gn/T/fnm_multishell_29633_1608062717331/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /var/folders/dj/fvcdsjcn3_s0g6cxb5kcq2wr0000gn/T/fnm_multishell_29633_1608062717331/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 27, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.6858069
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: ~0.63.3 => 0.63.4
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

I know I'm not providing a lot of extra info, but I'm not sure what would be helpful. I'm happy to provide whatever I can. 

Update:
I have tried creating a fresh react-native app + fresh library via bob. I still cannot install a new module inside a fresh react-native app. Is there some fundamental step I am missing?

**Comment by crherman7** [comment]
Hey @shorsher! I recently came across this issue - for me it was a metro-bundler / watchman issue not a `react-native-builder-bob` issue. What fixed this issue for me was running the following commands:

```
watchman watch-del-all
rm -rf $TMPDIR/metro*
rm -rf <project_folder>/node_modules
yarn install
yarn start --reset-cache
yarn run ios
```

*Note - each line is a separate command

Let me know if this helps!

**Comment by crherman7** [comment]
@shorsher please close this issue if these instructions worked for you so we can keep the issue list up-to-date and clean.

**Comment by shorsher** [comment]
@crherman7 Will do, thanks for the help!

**Comment by crherman7** [comment]
@shorsher oh dope dope! So those steps did work for me last week but I hit the issue again when revisiting a library I needed to update. This time I need to do a `yarn add ../` in the example folder and make sure the `package.json` has the correct library name.
