### ISSUE TITLE
How to disable sourcemap and ignore some file I don't want to be included?

### ISSUE THREAD

**Issue by chj-damon** [callstack/react-native-builder-bob#125]
## Ask your Question
In my library, I put `index.md` file with component source file. it looks like this way:
```
- component
    - index.tsx
    - index.test.ts
    - index.md
```

when running `bob build`, it will generate and then this component under `lib` folder will look like this:
```
- component
    - index.js
    - index.test.js
    - index.test.js.map
    - index.md
    - index.js.map
```
I don't want `index.js.map` and `index.md` and `test.js` after compiling. I wish the constructive should have only the `index.js` file.

What should I do?

**Comment by chj-damon** [comment]
solved by config `declarationMap`: false

**Comment by binhxn** [comment]
I'm currently running into this issue and tried adding `declarationMap: false` in several places in my **package.json**, but no luck. 

```json
"@react-native-community/bob": {
    "declarationMap": false,  
    "source": "src",
    "output": "dist",
    "targets": [
      "commonjs",
      "typescript"
    ]
  },
```

@chj-damon Where exactly did you add the `declarationMap` property?

**Comment by chj-damon** [comment]
@binhxn tsconfig

**Comment by hikitty2** [comment]
@chj-damon if not ts project，i how to set disable sourcemap
