### ISSUE TITLE
Auto linking assets (e.g: fonts)

### ISSUE THREAD

**Issue by bobbyecho** [callstack/react-native-builder-bob#126]
Hi team,

currently i have a problem with assets autolinking, im working in a library that use custom fonts

i wonder is it possible make the fonts auto linking in react-native >= 0.60?

i already create react-native.config.js

```
module.exports = {
  dependency: {
    assets: ['./assets/font']
  },
};
```

but have no luck

thanks..

**Comment by satya164** [comment]
The React Native CLI is responsible for handling linking, so please open issues regarding linking in the relevant repo https://github.com/react-native-community/cli

**Comment by gvamvoukas** [comment]
any news????

**Comment by satya164** [comment]
> any news????

What exactly do you expect here? This is a bootstrap tool. We can't do anything about how linking is handled.
