### ISSUE TITLE
Multiple "transform[stderr]: Could not resolve" errors in example app

### ISSUE THREAD

**Issue by IdkMan2** [callstack/react-native-builder-bob#127]
## Environment

```
MacBook Pro (13-inch, 2020, Two Thunderbolt 3 ports)
Mac OS Big Sur 11.1
Node v14.15.0
Yarn 1.22.10
```

Selected option during installation:
```
JavaScript library with Expo example and Web support
```

## Description
When I use the Expo sample app, I see a lot of bugs in the console (code and screenshot below). The app appears to be working fine and the bugs are not fatal, yet it does massive console spam. I did some research and tried to fix the problem myself but found nothing useful.

Console output:
```text
Logs for your project will appear below. Press Ctrl+C to exit.
transform[stderr]: Could not resolve "/Users/arkadiusznurzynski/Documents/CodeCloud/WebStorm/react-native-styles/src/index" in file /Users/arkadiusznurzynski/Documents/CodeCloud/WebStorm/react-native-styles/example/src/App.tsx.
transform[stderr]: Could not resolve "/Users/arkadiusznurzynski/Documents/CodeCloud/WebStorm/react-native-styles/src/index" in file /Users/arkadiusznurzynski/Documents/CodeCloud/WebStorm/react-native-styles/example/src/MyFunctionComponent.tsx.
Finished building JavaScript bundle in 20737ms.
Running application on MI 8 Lite.
```

![image](https://user-images.githubusercontent.com/23725071/103466284-de244a80-4d43-11eb-9625-e4d0850ebc3a.png)

## Reproducible Demo

Whole app can be found under this public repo:
https://github.com/IdkMan2/react-native-styles

**Comment by shamilovtim** [comment]
I get these a lot and I'm not sure what's causing them but I can confirm that they're part of the default setup of bob
