### ISSUE TITLE
Move index.d.ts outside the lib folder

### ISSUE THREAD

**Issue by yuranga-organization** [callstack/react-native-builder-bob#128]
## Ask your Question

Hello guys, first of all I want to say thank you for the great library. I am really appreciated.

My question is, whenever I run the command `npm run prepare`, the file `index.d.ts` will be put in the `lib` folder. What can I do to put the `index.d.ts` at root folder?

I changed the path as below, but it is not working.

```
{
  "name": "package-storage",
  "version": "0.1.0",
  "description": "This is a main storage module for mobile app",
  "main": "lib/commonjs/index",
  "module": "lib/module/index",
  "types": "index.d.ts",      // <=== This is the path of my index.d.ts
  "react-native": "src/index",
  "source": "src/index",
  ...
}
```

If you have any idea, please let me know. Thank you in advance!

**Comment by satya164** [comment]
The generated type definitions match the folder structure of the source files. So you can't move file to the root.

You could however create a separate index.d.ts file which imports everything from lib/typescript/index.d.ts and re-exports them. But why do you need to do this?

**Comment by yuranga-organization** [comment]
HI @satya164 , thank you for the quick comment. 

The reason I need it because when I publish the package and install it in my project by using `import` syntax, it require an index.d.ts

If not, my IDEA will underline the import as an error which is annoying to me.

**Comment by satya164** [comment]
You shouldn't need index.d.ts at root for that. The types field should take care of that.

If you changed the folder structure after generating the project, just make sure that the path in the types field is still correct since it could be different after changing folder structure. If the file exists and the path in types field is correct, it should just work in everywhere.

**Comment by yuranga-organization** [comment]
Hello @satya164 , sorry I am not quite understand the `types field` you mentioned above. Can you please give me more details? Thank you in advance!

The reason I want to move the `index.d.ts` out is because this package should be used in many places. If we have to move it out manually whenever we use it, thing would be inconvenient

**Comment by satya164** [comment]
I'm not really sure what details you're asking for. Like I said, you don't need to do anything to make it work as long as the path to index.d.ts mentioned in types field is correct. Doesn't matter if you're using the package in several places. You never been to manually move anything.

**Comment by yuranga-organization** [comment]
@satya164 Thank you for discussing with me. I found a way to solve the problem now. I am going to close this issue
