### ISSUE TITLE
Alternative for `prepare` script to work around https://github.com/yarnpkg/yarn/issues/7212

### ISSUE THREAD

**Issue by lfalkner** [callstack/react-native-builder-bob#13]
Is there an alternative to where `bob build` can run that does not involve using the `prepare` script? 

There is a [known issue](https://github.com/yarnpkg/yarn/issues/7212) with `yarn` that causes a second `yarn` process to spin up when a git package contains a `prepare` script. This makes it difficult to contribute to open source for any package which has such a script.

If there is an alternative to when and where the `bob build` script should run, that would be ideal.

**Comment by lfalkner** [comment]
Note this work-around worked for us: https://github.com/yarnpkg/yarn/issues/7212#issuecomment-487930971

Happy to contribute back a documentation update if you'd like

**Comment by satya164** [comment]
Closing since we use `prepack` script now instead.
