### ISSUE TITLE
C++: how to correctly import headers from react-native node_modules directory?

### ISSUE THREAD

**Issue by savv** [callstack/react-native-builder-bob#131]
Hi! I wrote a superfast JSI binding for leveldb - https://github.com/greentriangle/react-native-leveldb

There is one detail left to iron out. My library imports headers from react-native/JSI. On Android, I include a bunch of directories in the CMakeLists.txt file.

I can't quite figure out how to make the paths work both when the library is installed in a RN project and when I run `yarn example android`.
In the former case, the node_modules folder is located one level above my library. In the latter, the node_modules folder is inside my library.
So in order to make the library work (and break the android example), I had to do this:
https://github.com/greentriangle/react-native-leveldb/commit/2b54ef96b7461213e929d5e478749c813650fa3a

I tried to invent something with ${PROJECT_SRC_DIR} but couldn't figure out. Any help would be greatly appreciated!

Many thanks for providing this builder - it was a breeze to use.

**Comment by savv** [comment]
I was able to fix this by passing the node modules dir to CMAKE, like this:

https://github.com/greentriangle/react-native-leveldb/commit/371e56a63077271526701cc4dd2c475988bfbf3a

**Comment by chanphiromsok** [comment]
I struggling with JSI template it would be good to have options for JSI tempalte

**Comment by chanphiromsok** [comment]
> Hey @chanphiromsok If you have some ideas around it, please feel free to create a new discussion. Would be more than happy to talk.

I'm happy with that I will open issue😄🎉
