### ISSUE TITLE
Native view in Swift and Kotlin Creates a Project with Objective C and not swift

### ISSUE THREAD

**Issue by murtazabeans** [callstack/react-native-builder-bob#135]
## Ask your Question

I am using react-ative-builder-bob to create my project but when I select native view in Kotlin and Swift it still created objective c + kotlin project. I am unable to start the implementation as I want my native view to be in swift. Is there anything I am missing?

**Comment by nigimaxx** [comment]
The problem seems to be that `type === 'native-view-swift'` is missing from this line.
https://github.com/callstack/react-native-builder-bob/blob/main/src/create.ts#L354

**Comment by BartoszKlonowski** [comment]
Most probably it's already fixed by #129 
@murtazabeans  I've double checked that Bob creates Kotlin & Swift view correctly, but before I close the issue it would be great if you could confirm on your side.

**Comment by murtazabeans** [comment]
I think it is fixed. Closing the issue now
