### ISSUE TITLE
Types of library not being recognized

### ISSUE THREAD

**Issue by hannojg** [callstack/react-native-builder-bob#140]
## Ask your Question
I am not sure whether this a bug, but I believe it is just a misconfiguration.
I created a react native lib using typescript, swift, kotlin. This is the library: https://github.com/cuvent/react-native-better-tus-client
The module should be imported like this:
```js
import BetterTusClient from "@cuvent/react-native-better-tus-client";
```

However, my idea (webstorm) complains that it can't find any types for `BetterTusClient`:
> TS7016: Could not find a declaration file for module '@cuvent/react-native-better-tus-client'. '/Users/hannogodecke/Cuvent/app/Cuvent/node_modules/@cuvent/react-native-better-tus-client/lib/commonjs/index.js' implicitly has an 'any' type.   Try `npm i --save-dev @types/cuvent__react-native-better-tus-client` if it exists or add a new declaration (.d.ts) file containing `declare module '@cuvent/react-native-better-tus-client';`

The `lib/typescript/index.d.ts` file exists in the dir `node_modules/@cuvent/react-native-better-tus-client`, and in the `package.json` this file is named as `types` definition.

My (ugly) hotfix is to add this to the project, which is of course not desirable:
```typescript
declare module "@cuvent/react-native-better-tus-client" {
  import BetterTusClient from "@cuvent/react-native-better-tus-client/lib/typescript";
  export default BetterTusClient;
}
```

Any help is greatly appreciated 🙌

**Comment by satya164** [comment]
Hey, you can change this path to `lib/typescript/index.d.ts`

https://github.com/cuvent/react-native-better-tus-client/blob/b7f791f9025cebf39765743ba23bc7edd731c0ff/package.json#L7

The latest version generates the correct path.

**Comment by hannojg** [comment]
oh wow, this was me overseeing the obvious. Big thanks!
