### ISSUE TITLE
Polygons rendering

### ISSUE THREAD

**Issue by angeltodorovyara** [callstack/react-native-builder-bob#143]
## A lot of polygons rendering

I'm using React Native with Expo and I currently want to render roughly about 3000 polygons but the app is vary laggy on zoom. Is that normal behaviour that react-native-maps just cannot take the load or there is a way to optimise it? Thank you.
I'm using Google maps for both android and iOS via GOOGLE_PROVIDER
And is there something similar to leaflet-react but for Native apps. I know that I can use it inside a WebView but what's the point of react native then.

**Comment by Krizzu** [comment]
Hey, this sounds like question not related to this repo. You can try posting it at [Stackoverflow, react-native tag](https://stackoverflow.com/questions/tagged/react-native)
