### ISSUE TITLE
Flipper: 'event2/event-config.h' file not found 

### ISSUE THREAD

**Issue by thertzelle** [callstack/react-native-builder-bob#144]
## Ask your Question

I'm running the instructions to create a module and run the example, but it seems there is an issue with Flipper?

In the end I get: `example/ios/Pods/Headers/Public/libevent/event.h:44:10: fatal error: 'event2/event-config.h' file not found`

Does anyone have any suggestions for what I can do to fix this issue?

**Comment by thertzelle** [comment]
The only difference I see is that one machine will build cocoalibevent and the other libevent. The cocalibevent is working and the libevent one is not. Anyone have any ideas?

**Comment by satya164** [comment]
@thertzelle did you find a fix to your issue?

**Comment by mlazari** [comment]
I had this issue today too. It looks like there were some incompatible Flipper dependencies in `example/ios/Podfile.lock`. I think it was `Flipper-Folly`, but not 100% sure since the Podfile.lock file was uncommited and I didn't commit it before making changes. Maybe it worth creating `example/ios/Podfile.lock` at the moment when the project is created, with compatible/working versions? I don't think it was created for me until I ran `yarn example ios`.
The working versions for me in `example/ios/Podfile.lock` are:
```
  - Flipper (0.54.0):
    - Flipper-Folly (~> 2.2)
    - Flipper-RSocket (~> 1.1)
  - Flipper-DoubleConversion (1.1.7)
  - Flipper-Folly (2.3.0):
    - boost-for-react-native
    - CocoaLibEvent (~> 1.0)
    - Flipper-DoubleConversion
    - Flipper-Glog
    - OpenSSL-Universal (= 1.0.2.20)
  - Flipper-Glog (0.3.6)
  - Flipper-PeerTalk (0.0.4)
  - Flipper-RSocket (1.1.1):
    - Flipper-Folly (~> 2.3)
  - FlipperKit (0.54.0):
    - FlipperKit/Core (= 0.54.0)
  - FlipperKit/Core (0.54.0):
    - Flipper (~> 0.54.0)
    - FlipperKit/CppBridge
    - FlipperKit/FBCxxFollyDynamicConvert
    - FlipperKit/FBDefines
    - FlipperKit/FKPortForwarding
  - FlipperKit/CppBridge (0.54.0):
    - Flipper (~> 0.54.0)
  - FlipperKit/FBCxxFollyDynamicConvert (0.54.0):
    - Flipper-Folly (~> 2.2)
  - FlipperKit/FBDefines (0.54.0)
  - FlipperKit/FKPortForwarding (0.54.0):
    - CocoaAsyncSocket (~> 7.6)
    - Flipper-PeerTalk (~> 0.0.4)
  - FlipperKit/FlipperKitHighlightOverlay (0.54.0)
  - FlipperKit/FlipperKitLayoutPlugin (0.54.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitHighlightOverlay
    - FlipperKit/FlipperKitLayoutTextSearchable
    - YogaKit (~> 1.18)
  - FlipperKit/FlipperKitLayoutTextSearchable (0.54.0)
  - FlipperKit/FlipperKitNetworkPlugin (0.54.0):
    - FlipperKit/Core
  - FlipperKit/FlipperKitReactPlugin (0.54.0):
    - FlipperKit/Core
  - FlipperKit/FlipperKitUserDefaultsPlugin (0.54.0):
    - FlipperKit/Core
  - FlipperKit/SKIOSNetworkPlugin (0.54.0):
    - FlipperKit/Core
    - FlipperKit/FlipperKitNetworkPlugin
```

**Comment by troZee** [comment]
@mlazari 
Thank you for providing podlock.file, but it did not work on my end. I used https://github.com/callstack/react-native-viewpager/edit/master/example/ios/Podfile.lock and everything works fine. 

Below I am posting a terminal log: 
```bash 
➜  ios git:(master) ✗ pod install
Analyzing dependencies
Downloading dependencies
Installing CocoaLibEvent (1.0.0)
Installing Flipper-Folly 2.3.0 (was 2.5.1)
Installing Flipper-RSocket 1.1.0 (was 1.3.0)
Installing OpenSSL-Universal 1.0.2.20 (was 1.1.180)
Removing libevent
Generating Pods project
Integrating client project
Pod installation complete! There are 48 dependencies from the Podfile and 39 total pods installed.
```

**Comment by mlazari** [comment]
Maybe it was something else... attaching the full Podfile.lock file that works for me in case it's helpful:
[Podfile.lock.txt](https://github.com/callstack/react-native-builder-bob/files/6108454/Podfile.lock.txt)

**Comment by thertzelle** [comment]
@mlazari Thank you so much you're Podfile.lock works great!

This was the output after running `pod install` after switching the dep. CocoaLibEvent works and libevent does not.

```
Downloading dependencies
Installing CocoaLibEvent (1.0.0)
Installing Flipper-Folly 2.3.0 (was 2.5.1)
Installing Flipper-RSocket 1.1.1 (was 1.3.0)
Installing OpenSSL-Universal 1.0.2.20 (was 1.1.180)
Removing libevent
```

**Comment by Aure77** [comment]
I got same issue. I solved it by explicitly setting another (newer) version on Flipper:

ex:
`use_flipper!({ 'Flipper' => '0.80.0' })`
https://fbflipper.com/docs/getting-started/react-native/#using-the-latest-flipper-sdk
