### ISSUE TITLE
Incorrect bob version in package.json file

### ISSUE THREAD

**Issue by troZee** [callstack/react-native-builder-bob#145]
## Environment

MacOS

## Description

* `npx create-react-native-library react-native-awesome-module`
* `cd  react-native-awesome-module`
* `yarn bootstrap`

## Reproducible Demo

![Screen Shot 2021-03-09 at 11 36 29 AM](https://user-images.githubusercontent.com/12766071/110458554-2e18e800-80cc-11eb-851e-128d5a14058a.png)

**Comment by Krizzu** [comment]
Hello @troZee 

Looks like [npm view](https://github.com/callstack/react-native-builder-bob/blob/main/packages/create-react-native-library/src/index.ts#L329-L336) returned empty response instead a version. Are you able to reproduce it every time?
I just tried couple of times and I get the correct version.

**Comment by troZee** [comment]
Hello @Krizzu 
Thank you for checking this issue. I am still able to reproduce it on my end. 

Below I am providing more info to reproduce it
![Screen Shot 2021-03-11 at 12 48 30 PM](https://user-images.githubusercontent.com/12766071/110783394-addbb980-8268-11eb-936c-0619f13decef.png)

**Comment by prolok** [comment]
I have seen this too and I have to manually add the react-native-builder-bob by calling

```
yarn add --dev react-native-builder-bob
```
