### ISSUE TITLE
Dependency issue: Google play services required 

### ISSUE THREAD

**Issue by TfADrama** [callstack/react-native-builder-bob#146]
## Ask your Question

My lib, on the android side, needs the google play services to work. 
On the example project i added the play services, but my lib is throwing an exception saying that i need to add the services to the project. 
So, maybe i need to add some "peer dependency" on the lib in order to recognise the services from the example project. Is this possible?

**Comment by Krizzu** [comment]
If you mean Google Play Services on device, it is not a library, but rather an [app (background services)](https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en&gl=US), that comes preinstalled on devices accessing Google services (maps, calendar etc.).

What exactly is the issue you see?

**Comment by satya164** [comment]
Sounds like an issue with GemiusSDK then? Bob doesn't prevent you from using any libraries.

The setup here is pretty standard, you have a lib which is linked to an app. If you add something to the example app, it would be equivalent to user adding it. Either you used different version or there's some setup required by your SDK.
