### ISSUE TITLE
Adding type support to a JavaScript project

### ISSUE THREAD

**Issue by tsdmrfth** [callstack/react-native-builder-bob#150]
Hi. First thanks for this great library. Helped me a lot.

I developed a React Native component package using JavaScript and wanted to add type support for those who use TypeScript but I couldn't do that. I added a index.d.ts file to both root and src directories but an index.d.ts is not being generated under lib/typescript folder. What I am missing?

**Comment by satya164** [comment]
The files under `lib` are generated files. If you're writing `.d.ts` files by hand, then there's nothing to generate. You just need to specify the path to `index.d.ts` in the `types` field in your `package.json`.
