### ISSUE TITLE
Watch command is not rebuilding

### ISSUE THREAD

**Issue by buffaloDeveloper** [callstack/react-native-builder-bob#151]
Maybe I'm using "watch" incorrectly.

I want to watch for changes under the './src/' directory.

When I make a change all I see is message stating it's a directory, the rebuild is not triggered...

➜  yyy-ui-components git:(master) ✗ yarn watch ./src/ 
yarn run v1.22.10
$ /Users/xxx/workspace/nextga/yyy-ui-components/node_modules/.bin/watch ./src/
> Watching /Users/xxx/workspace/yyy/yyy-ui-components
sh: ./src/: is a directory
sh: ./src/: is a directory
sh: ./src/: is a directory

**Comment by satya164** [comment]
There's no `watch` command in the default template, and you don't need to watch for any changes. You just run the example app and make your changes, and it'll reflect your changes.

**Comment by buffaloDeveloper** [comment]
> There's no `watch` command in the default template, and you don't need to watch for any changes. You just run the example app and make your changes, and it'll reflect your changes.

What if I am working outside of the example app?

**Comment by satya164** [comment]
Like I said, you just make your changes and everything works like I supposed to. There's nothing to watch or build unless you're publishing.

**Comment by buffaloDeveloper** [comment]
Maybe I'm not explaining this correctly.  I have deleted the "example" folder (not using it).  I created a folder called "src" and all my library components are being created there.  I want to run "bob build" whenever I make and save changes in the "src" folder.  This is not working currently and I need to manually run "yarn prepare" to trigger the build.

➜  xxx-ui-components git:(master) ✗ yarn prepare          
yarn run v1.22.10
$ bob build
ℹ Building target commonjs
ℹ Cleaning up previous build at lib/commonjs
ℹ Compiling 6 files in src with babel
✔ Wrote files to lib/commonjs
ℹ Building target module
ℹ Cleaning up previous build at lib/module
ℹ Compiling 6 files in src with babel
✔ Wrote files to lib/module
ℹ Building target typescript
ℹ Cleaning up previous build at lib/typescript
ℹ Generating type definitions with tsc
✔ Wrote definition files to lib/typescript
✨  Done in 2.27s.

**Comment by buffaloDeveloper** [comment]
This works for me:

nodemon --watch src --exec yarn prepare

**Comment by axhamre** [comment]
> There's no watch command ...

@satya164 What do you mean? There's clearly a `watch` command stated [in the README](https://github.com/callstack/react-native-builder-bob#development-workflow).

**Comment by satya164** [comment]
> There's clearly a watch command stated in the README

The README is for this library, not for generated project

**Comment by axhamre** [comment]
> The README is for this library, not for generated project

OK sory, my bad 👍

**Comment by axhamre** [comment]
@buffaloDeveloper Thank you very much!

For whomever this could help, for TS files the `nodemon` command has to be extended, e.g.:

`"watch": "nodemon --watch src --exec 'yarn prepare' -e tsx"`

**Comment by a-eid** [comment]
> Like I said, you just make your changes and everything works like it's supposed to. There's nothing to watch or build unless you're publishing.

it's not working like you described.

**Comment by buffaloDeveloper** [comment]
Yeah, I couldn't get it to build automatically, so I've been using nodemon for the past year.  

My only complaint is I've got 180 files, and every single file gets rebuilt on changes - this can take up to 20 seconds on my laptop to complete the build.

**Comment by satya164** [comment]
> it's not working like you described, building is required on every change.

If it's not working then please open an issue with a repro. Though I have been using this in several libraries and never had an issue. Unless you changed something in the way the example app is configured (babel alias, package.json keys, metro config), then there's no reason it wouldn't work.

**Comment by a-eid** [comment]
@satya164 will try to test on a clean generated project.
