### ISSUE TITLE
`index.android.ts` and `index.ios.ts` files support

### ISSUE THREAD

**Issue by SudoPlz** [callstack/react-native-builder-bob#156]
Hey there,

Is there anything we should do to get correct types for index.android.ts` and `index.ios.ts` files?

I'm maintaining this library https://github.com/SudoPlz/sp-react-native-in-app-updates/tree/master/src and I'm trying to get the types right (2 separate modules one for iOS and 1 for Android with the same api but working differently below the hood).

How do I make that work?

Thanks

**Comment by satya164** [comment]
You need to create a `index.ts` file and then platform specific files. That file could just expose the same type, but throw error when using it. That'd not only make it work with TypeScript, but also throw a proper error on unsupported platforms like web, windows & mac.
