### ISSUE TITLE
Cannot find module '*' or its corresponding type declarations.ts

### ISSUE THREAD

**Issue by waltermvp** [callstack/react-native-builder-bob#183]
## Environment

Latest npx project build im using node 14.17

## Description

despite adding a library dependency to deps, peerdeps, & devDeps (in this case ramba) i still get an error when attempting to import the dep.

## Reproducible Demo
https://www.dropbox.com/s/roa64r7fm7x7051/react-native-ui.zip?dl=0

**Comment by ttristan** [comment]
I have multiple repos and I noticed this issue as well after renaming some package. Looking at your package.json it says `@epiphanyapps/react-native-ui` - did you change this after creating the package? That might be the reason.
