### ISSUE TITLE
optimize package local dev experience

### ISSUE THREAD

**Issue by DeepRolling** [callstack/react-native-builder-bob#185]
## Describe the feature

sometimes I want to develop a toolkit package use for several applications, so before publishing this package to the registry,I need depend this package locally .
when I use command **yarn add yarn add /Volumes/MAC2/somelib/mylib** add my package to my project, the node_modules in my package also be added to my project. 
so it is best to add preinstall script to package.json generator : 
` 
"scripts": {
    "preinstall": "rm -rf node_modules",
  },
`

## Motivation

optimize local dev experience.

**Comment by satya164** [comment]
I recommend using https://verdaccio.org/ to publish the module to a local registry to test it.
