### ISSUE TITLE
how it can understand local package name without using `yarn link` or any other solution

### ISSUE THREAD

**Issue by TheEhsanSarshar** [callstack/react-native-builder-bob#189]
## Ask your Question

I can import my local library inside example folder  `import X from 'react-native-x'`
how it's possible?

**Comment by gate3** [comment]
+1

**Comment by satya164** [comment]
There is an alias (https://github.com/callstack/react-native-builder-bob/blob/94c1fbe9b43643c45dbbbfa092752c28c7fbc9f5/packages/create-react-native-library/templates/example/example/babel.config.js#L12) to the library's source code which makes this possible.
