### ISSUE TITLE
Allow configuring ignore/exclude files settings

### ISSUE THREAD

**Issue by koiralakiran1** [callstack/react-native-builder-bob#197]
## Describe the feature
As mentioned here: https://github.com/callstack/react-native-builder-bob/issues/162, ignore files settings is not exposed via the configuration. Maybe `**/{__tests__,__fixtures__,__mocks__}/**` could be made as default, if no exclude settings were provided?

## Motivation
I was going through [this issue](https://github.com/akinncar/react-native-mask-text/issues/29) and found that the project is using this package, which doesn't support configuring exclude settings.

## Related Issues
https://github.com/callstack/react-native-builder-bob/issues/162

**Comment by trajano** [comment]
How is this configured?  I'm still getting tests in the lib folder and when I do `yarn pack`
