### ISSUE TITLE
"expo-splash-screen" is added as a dependency

### ISSUE THREAD

**Issue by zrg-team** [callstack/react-native-builder-bob#204]
## Environment

node v14.17.6

## Description

"expo-splash-screen" is added as a dependency in your project's package.json but it doesn't seem to be installed. Please run "yarn" or "npm install" to fix this issue.

if i install "expo-splash-screen" 

![image](https://user-images.githubusercontent.com/38390571/138131546-44f576ab-6096-4a96-9e98-5c4c3c1e702f.png)

## Reproducible Demo

```
npx create-react-native-library react-native-awesome-module
-> js only
yarn install
yarn example web
```

**Comment by R3ahim** [comment]
wow

**Comment by satya164** [comment]
Closing since I cannot repro this. If you still have an issue, please provide a repro project.
