### ISSUE TITLE
Upgrade to RN 0.66+

### ISSUE THREAD

**Issue by wilsolutions** [callstack/react-native-builder-bob#207]
## Describe the feature

Upgrade the package.json to generate modules with 0.66+ RN.

## Motivation

React Native is on version o.66.1 https://github.com/facebook/react-native/releases/tag/v0.66.1 but the modules generated with this library are sstill on 0.63.

## Related Issues

It is good to keep modules updated.

**Comment by youngjuning** [comment]
+1

**Comment by jp928** [comment]
+ 1

**Comment by Alexufo** [comment]
+

**Comment by davidjytang** [comment]
If maintainer could indicate what are the gotchas or what to watch out for, we might be able to send in a pull request on the version upgrade on RN.

Maybe I'm just being naive on this.

**Comment by HurrellT** [comment]
I did a manual update and seems to be working fine.

**Comment by Alexufo** [comment]
@HurrellT yes, example works with latest RN. But not with react-native-builder-bob

**Comment by krmao** [comment]
anything about 0.69.+ @satya164

**Comment by MateWW** [comment]
We are actively working on migration to 0.70 🙂 
@atlj
