### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

### ISSUE THREAD

**Issue by Alexufo** [callstack/react-native-builder-bob#213]
windows. Expo demo app works. 
But I tried to create demo module  `npx create-react-native-library react-native-awesome-module`

After `yarn example android`

And I get `No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi`

![image](https://user-images.githubusercontent.com/1562329/143059443-2e37217c-87d5-40f7-ac55-370de0ad069d.png)

**Comment by Bressan09** [comment]
Which version of the android NDK are you using?
I got this same issue with the latest version from android studio (v23), switched back to v22 and it worked.
Hope this can help: https://stackoverflow.com/a/66922163/13557464

**Comment by Alexufo** [comment]
I clean all NDK in android folders and it works
