### ISSUE TITLE
Why eslint-config-prettier and eslint-plugin-prettier are needed in devDependencies

### ISSUE THREAD

**Issue by rnike** [callstack/react-native-builder-bob#219]
Saw two dependencies that are not directly be used in the project created but still in the `devDependencies`, wondering why.

The packages are `eslint-config-prettier` and `eslint-plugin-prettier`, they have been added in package.json when the project is created

https://github.com/callstack/react-native-builder-bob/blob/75a4a3cf1b7d5f3c2b14f2f3a20c0be72250a119/packages/create-react-native-library/templates/common/%24package.json#L58-L59

Due to they are already dependencies of `@react-native-community/eslint-config`, I thought it should be okay to delete them from package.json, but not 100% sure if they are added for any purpose.

**Comment by vonovak** [comment]
hello, they are used in package.json, see eg. here 

https://github.com/callstack/react-native-builder-bob/blob/866bc5acdaba778886bdc6be351e3e3df217ac6b/packages/create-react-native-library/templates/common/%24package.json#L107

thank you
