### ISSUE TITLE
Allow polyfilling & bundling

### ISSUE THREAD

**Issue by tex0l** [callstack/react-native-builder-bob#222]
## Describe the feature

I'd like to have a way to add polyfills to my library. What I have in mind is a pre / post build stage where I could use webpack.

## Motivation

For example, I'm working on a library which relies on Buffer and stream, and more generally, some dependencies of that library depend on those packages.

I'd like to export a built bundle a developer can import without asking questions (as well as the bare files where he'd need to do the polyfilling themself in the metro config).

**Comment by satya164** [comment]
Closing as duplicate of https://github.com/callstack/react-native-builder-bob/issues/182
