### ISSUE TITLE
Upgrade react-native create-react-native-library

### ISSUE THREAD

**Issue by jspizziri** [callstack/react-native-builder-bob#231]
## Describe the feature

Upgrade the `example`  generated by `create-react-native-library`  to contain a modern version of `react-native` (it's currently `v0.63.4`.

## Motivation

This is a 2yr old release and for new libs, it's probably a good idea to base off of a modern version of `react-native`. This old of a version causes issues when trying to install more modern packages in your `example` app (e.g. `react-native-safe-area-context`).

## Related Issues

https://github.com/th3rdwave/react-native-safe-area-context/issues/246#issuecomment-1065401305

**Comment by ugglr** [comment]
An upgrade would be nice 👍

**Comment by dyerw** [comment]
This would be hugely valuable to me as well :+1:

**Comment by satya164** [comment]
The latest version now uses RN 0.68
