### ISSUE TITLE
New architecture support?

### ISSUE THREAD

**Issue by a7medev** [callstack/react-native-builder-bob#238]
## Describe the feature

Support for generating libraries that target the new and the old architectures at once, kinda like what is being done here: [react-native-community/RNNewArchitectureLibraries](https://github.com/react-native-community/RNNewArchitectureLibraries).

## Motivation

The React Native team has started to roll out the new architecture starting with version 0.68 and more and more libraries are adding support to it and it would be really great to be able to start building libraries targeting both the old and the new architectures as smoothly as it is the case now for the old architecture (native modules).

**Comment by HurrellT** [comment]
I would also love to know how to upgrade a project to a new version of bob builder and configurations
