### ISSUE TITLE
How to build absolute path?

### ISSUE THREAD

**Issue by buuhvprojects** [callstack/react-native-builder-bob#241]
I had configured absolute path in tsconfig but when I build it, the absolute path import doesnt change, It still have absolute import and babel doesnt change to normal import, so when i use my lib in some project, the project doesnt undestand absolute path inside lib files.

**Comment by murilogok** [comment]
+1

**Comment by devleonardorabelo** [comment]
+ 1

**Comment by satya164** [comment]
You can configure Babel to change the paths by using a plugin like `babel-plugin-module-resolver`. To use your own babel config, set `configFile: true`

https://github.com/callstack/react-native-builder-bob#commonjs

**Comment by brunomacedo** [comment]
+1
