### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'

### ISSUE THREAD

**Issue by felire** [callstack/react-native-builder-bob#242]
## Ask your Question

I am creating a library and I am getting this error:

```
Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'
```
For every children i want to set to a React Native element such as `View`, `Text`, `Animated.View`. 

Any idea or suggestion on how can I resolve that?

**Comment by bufgix** [comment]
Same here 😔

**Comment by atlj** [comment]
you can solve this by updating types for react native
```bash
yarn add @types/react-native -D
```
