### ISSUE TITLE
Why example/ios/Pods also published when run "yarn publish"?

### ISSUE THREAD

**Issue by chocking** [callstack/react-native-builder-bob#251]
I created a react-native api lib and its package.json with a files field like
```
"files": [
    "src",
    "lib",
    "android",
    "ios",
    "cpp",
    "<my-lib-name>.podspec",
    "!lib/typescript/example",
    "!android/build",
    "!ios/build",
    "!**/__tests__",
    "!**/__fixtures__",
    "!**/__mocks__"
  ],
```
When I run ```yarn publish```, it pended for a long time, finally I found that It was pushing the ```example/ios/Pods``` to repository, I removed the fields begins with ```!``` in package.json#files then everything look well.
I wonder why these fields generated, the [docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files) of package.json#files doesn't mention the exclude(path begins with ```!```) feature

**Comment by satya164** [comment]
You should use the preconfigured release script which internally uses `npm` that has correct publishing behaviour: https://github.com/callstack/react-native-builder-bob/blob/main/packages/create-react-native-library/templates/common/CONTRIBUTING.md#publishing-to-npm

**Comment by chocking** [comment]
> You should use the preconfigured release script which internally uses `npm` that has correct publishing behaviour: https://github.com/callstack/react-native-builder-bob/blob/main/packages/create-react-native-library/templates/common/CONTRIBUTING.md#publishing-to-npm

okok
