### ISSUE TITLE
How to embed a 3rd party library into my library instead of adding as peer dependency

### ISSUE THREAD

**Issue by soubhratra-instnt** [callstack/react-native-builder-bob#257]
This FAQ recommends, https://github.com/callstack/react-native-builder-bob#how-do-i-add-a-react-native-library-containing-native-code-as-a-dependency-in-my-library, to declare a react native library as peer and dev dependency into another react-native library and then add it to the consumer app as dependency.

I am building a react native SDK / library, that will be used by multiple customer apps. My react native library need to include (use) another react native library which provides important runtime capability but does not get exposed to the customer apps. In fact, we do not want to expose this dependency to the customer to reduce the complexity on integration / use of our library. This is also a very specialized library which customer will not pull from any other dependencies.

Is it possible to embed (declare as direct dependency instead of peer dependency) a react native library into another react native library?

**Comment by satya164** [comment]
It's not possible. If you don't want the consumer to install the library then you need to copy that code into your library and change the module name to avoid conflicts.

**Comment by soubhratra-instnt** [comment]
Thanks Satya for your response. To best of my knowledge, this is different from how Javascript dependencies are added to npm  libraries where we can declare a sub-dependency in your library module and if its not a plugin, it will be resolved and used in host application. https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependencies

Is that a correct assessment?  Just trying to understand as in my case, the sub-dependency is entirely confined in my library and are not exposed to the host app directly. TYA.

**Comment by satya164** [comment]
This is mentioned in the FAQ link

> While there can be multiple versions of a JavaScript-only library, there can only be one version of a native library - so avoiding version conflicts is important

Native modules/components are singletons. There can be only one instance of a native module/component. Unless you can guarantee that the user will never install that dependency in their app or install a library using that dependency, then there's a chance of conflicts.

**Comment by soubhratra-instnt** [comment]
Thanks for pointing out the relevant documentation. I guess as NPM 7 onwards peer dependencies are installed automatically, which reduces the overhead of the host applications to manage such dependencies if they do not need to. https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies
