### ISSUE TITLE
3rd party maven dependency in react-native npm module

### ISSUE THREAD

**Issue by DanielFrTB** [callstack/react-native-builder-bob#259]
Hi, 
I am trying to use 3rd party SDK in my react-native android module.

and I have got the same problem here:
[https://github.com/callstack/react-native-builder-bob/issues/63](url)

It seems like the module can't find the SDK and looking in the wrong place.

it only finds the SDK if I specified the in the 
`maven {
    url "xxxxx"

 }`

inside the Example-app build.gradle, the problem is that I am spcified is twice, first in the module build.gradle and the second time inside Example-app build.gradle, is it the right approach?

**Comment by rajeevverma076** [comment]
If I need to add @react-native-community/datetimepicker in my project. how I will do. If I'm adding to peerDependencies it is not calling import DateTimePicker from '@react-native-community/datetimepicker'; it is throwing an error. 
kindly suggest
