### ISSUE TITLE
[Question] Package with multiple `exports` folders

### ISSUE THREAD

**Issue by kaueDM** [callstack/react-native-builder-bob#260]
## Ask your Question

How can I setup builder-bob to output multiple `exports`?

I want to export some `utils` in a different path (like "/my-lib/utils"), but couldn't figure it out yet looking the source code/issues.

**Comment by alpha0010** [comment]
Sort of a hack, but here is how I did it: https://github.com/alpha0010/react-native-pdf-viewer/commit/c7c41ea12b7b5742ffa60d1cc4acdadaf582192f .

- Write all your code in `src/`
- Register a redirect in a subdirectory
```js
// In utils/package.json
{
  "main": "../lib/commonjs/MyScript",
  "module": "../lib/module/MyScript",
  "react-native": "../src/MyScript",
  "types": "../lib/typescript/MyScript.d.ts"
}
```

With this, `import { Xyz } from 'my-lib/utils';` should work when the library is installed.  (Requires some trickery to make this work in the example project, so not certain what to suggest there.)

**Comment by kaueDM** [comment]
Couldn't make it work, so I replaced `builder-bob` with `rollup`.

**Comment by dmahajan980** [comment]
@kaueDM can you share the repository so that we can see how you did it? Thanks

**Comment by zarkoden** [comment]
@kaueDM can you share your rollup solution, please?

**Comment by mikelgarciaurbina** [comment]
I share how I fix it:
Create a folder outside of the src for example if you have a src/utils that you want to export in a different path, create a utils folder and add a `package.json`:
/my-lib/utils/package.json
```json
{
  "main": "../lib/commonjs/utils",
  "module": "../lib/module/utils",
  "react-native": "../src/utils"
}
```
 And add this folder to the files of the main package.json:
 ```json
{
  "main": "lib/commonjs/index.js",
  "module": "lib/module/index.js",
  "react-native": "src/index.js"
  ...
  "files": [
    "build",
    "src",
    "utils"
  ],
}
```

With this one after you can do an import like this:
```js
import { someUtil } from 'my-lib/utils';
```
