### ISSUE TITLE
Unable to exclude example app and android/build folder from final build

### ISSUE THREAD

**Issue by akashS1997** [callstack/react-native-builder-bob#264]
In the default setup when I publish the package to the GitHub npm repository using **yarn publish** it basically publishes a npm package which has everything including the example app code.
So I want to exclude the example app folder and some other project files from the npm package. 
I tried using .npmignore file but still it's not working.

**Comment by MateWW** [comment]
Hey @akashS1997 
Please describe your problem correctly otherwise we will be unable to help.

**Comment by satya164** [comment]
Closing due to no response
