### ISSUE TITLE
Why i'm getting the initial create-react-native-library project when pushing on Github! 

### ISSUE THREAD

**Issue by ayech0x2** [callstack/react-native-builder-bob#266]
## Ask your Question

Why when I push on GitHub repository i get the initial created project with create-react-native-library?

Here is my npm package with latest version: 
https://www.npmjs.com/package/rn-exoplayer

And here my GitHub repository with the initial version! 
https://github.com/ayech0x2/rn-exoplayer

Any help please?

**Comment by MateWW** [comment]
Hey, 
Have you committed your changes?
https://www.atlassian.com/git/tutorials/saving-changes/git-commit
Our library will create only an initial commit for all other changes you have to commit on your own.

**Comment by satya164** [comment]
Closing due to no response
