### ISSUE TITLE
Bootstrapping new project created from create-react-native-library does not work

### ISSUE THREAD

**Issue by frankbolviken** [callstack/react-native-builder-bob#283]
## Environment

Nothing special, just issued the following command from terminal
```
npx create-react-native-library@latest react-native-components
cd react-native-components
yarn
```

## Description

The script will fail with error:
```
....
✔ Wrote definition files to lib/typescript
$ yarn --cwd example pods
error Command "pods" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Whenever i try yarn example ios
```
✔ It looks like you're trying to use TypeScript but don't have the required dependencies installed. Would you like to install @types/react? … yes

✔ Installed @types/react@~17.0.21
It looks like you're trying to use TypeScript but don't have the required dependencies installed.

Please install @types/react by running:

yarn add --dev @types/react@~17.0.21

If you're not using TypeScript, please remove the TypeScript files from your project and delete the tsconfig.json.
```
It will present this error no matter if you installed the @types/react library.

**Comment by satya164** [comment]
Can you try again with the latest version?

**Comment by Splicer97** [comment]
> Can you try again with the latest version?

Yes, it is working now, thanks! Can you add background color white in example build in future?, because in example project start with black screen without result text.

**Comment by Splicer97** [comment]
> Can you try again with the latest version?

How can I fix my current project with previous version?

**Comment by satya164** [comment]
> How can I fix my current project with previous version?
You can generate a new project and copy over the files

**Comment by Alexufo** [comment]
update "scripts"  section in `package.json`  files in root and in example folder from generated new project.
