### ISSUE TITLE
Error on initialization of example app

### ISSUE THREAD

**Issue by bryanmehall** [callstack/react-native-builder-bob#286]
## Environment
Running with a global install of npx

## Description

Creating a react native library fails on initialization when creating example because the examples folder does not exist (see error below)
I also tried to create it with the native module option because it is not experimental and the command line tool made it one step further to the language selection option before failing with the same error after selecting C++.

## Reproducible Demo
```
npx create-react-native-library@latest react-native-common-lib
npx: installed 96 in 15.603s
✔ What is the name of the npm package? … react-native-common-lib
✔ What is the description for the package? … React native compatibility layer for the rust common library
✔ What is the name of package author? … Bryan Mehall
✔ What is the email address for the package author? … bryan@example.com
✔ What is the URL for the package author? … https://github.com/bryanmehall
✔ What is the URL for the repository? … https://github.com/bryanmehall/react-native-common-lib
✔ What type of library do you want to develop? › Turbo module with backward compat (experimental)
⠙ Generating example appcreate-react-native-library <name>

create a react native library

Options:
  --help          Show help                                            [boolean]
  --version       Show version number                                  [boolean]
  --slug          Name of the npm package                               [string]
  --description   Description of the npm package                        [string]
  --author-name   Name of the package author                            [string]
  --author-email  Email address of the package author                   [string]
  --author-url    URL for the package author                            [string]
  --repo-url      URL for the repository                                [string]
  --languages     Languages you want to use
      [choices: "java-objc", "java-swift", "kotlin-objc", "kotlin-swift", "cpp",
                                                                           "js"]
  --type          Type of library you want to develop
    [choices: "module-legacy", "module-turbo", "module-mixed", "module", "view"]
  --example       Type of example app                [choices: "expo", "native"]

[Error: ENOENT: no such file or directory, open '/home/bryan/app/react-native-common-lib/example/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/bryan/app/react-native-common-lib/example/package.json'
}

```

**Comment by kimdaxterkid** [comment]
Got same error when I run the npx command
It works for me to create a test module 2 days ago(10/11/2022), but it not works today(10/11/2022).

**Comment by cometman** [comment]
Same here...

**Comment by bryanmehall** [comment]
That fixed it! My global node version was ancient. Thank you!

**Comment by piotr-suwala** [comment]
That was exactly it. Thank you!

**Comment by KPS250** [comment]
I am on latest node V19.2.0. Still facing the issue.

[Error: ENOENT: no such file or directory, open '/Users/k14336/myworkspace/mobile/react-native-awesome-module/example/package.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/k14336/myworkspace/mobile/react-native-awesome-module/example/package.json'
}

**Comment by satya164** [comment]
> I am on latest node V19.2.0. Still facing the issue.
> 
> [Error: ENOENT: no such file or directory, open '/Users/k14336/myworkspace/mobile/react-native-awesome-module/example/package.json'] {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'open',
>   path: '/Users/k14336/myworkspace/mobile/react-native-awesome-module/example/package.json'
> }
> 

Are you using latest version of `create-react-native-library`?
