### ISSUE TITLE
Cannot run iOS example

### ISSUE THREAD

**Issue by Janaka-Steph** [callstack/react-native-builder-bob#300]
## Environment

Mac m1
create-react-native-library: 0.24.3

## Description

Creating new project with npx create-react-native-library@latest gdk
`yarn`
`yarn example ios`

Build fails with: 
- /Users/janaka/Desktop/gdk/ios/Gdk.h:4:35: No type or protocol named 'NativeGdkSpec'
- /Users/janaka/Desktop/gdk/ios/Gdk.mm:27:46: No member named 'NativeGdkSpecJSI' in namespace 'facebook::react'

**Comment by satya164** [comment]
Can you provide more details such as which options you chose?

**Comment by Janaka-Steph** [comment]
I have selected Turbo module with backward compat (experimental)
