### ISSUE TITLE
Native<PackageName>Spec doesn't exist on Android

### ISSUE THREAD

**Issue by CJxD** [callstack/react-native-builder-bob#315]
### Description

After building a fresh project, the Kotlin native module file tries to extend Native<PackageName>Spec but it hasn't yet been built.

```
class TestModule(val reactContext: ReactApplicationContext?) : NativeTestSpec(reactContext) {
                                                               ^^^^^^^^^^^^^^
```

I expected to see something in `android/generated/source/codegen` but the directory doesn't exist.

I see that builder-bob has not been set up to build an .aar - is this necessary to make it work?

I tried to reconfigure with .aar files enabled. I had to upgrade the Android Gradle plugin to 7.3.0 to work with the version of Gradle in use (7.4) and change the androidBundleName option from android.aar to android-release.aar. After this, it still refuses the build with the same error - nothing seems to be generating this class even if I comment out the code to make `npx bob build` run all the way through.

The test example I've given should reproduce, but I have also copied in the repository in which I am struggling to get set up which is a fairly simple API.

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

```
npx create-react-native-library@latest test \
    --slug "react-native-test" \
    --description "Test" \
    --author-name "Test" \
    --author-email "test@test.com" \
    --author-url "https://test.com" \
    --repo-url "https://github.com/test" \
    --languages kotlin-swift \
    --type module-turbo \
    --example native
```

### Link to repro

https://gitlab.com/numbereight/community/react-native-ne-euclid

### Environment

create-react-native-library v0.25.0

```
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-1280P
    Memory: 11.40 GB / 31.07 GB
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v19.0.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found (lies)
  IDEs:
    Android Studio: Not Found (also lies)
  Languages:
    Java: 11.0.16 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0 
    react-native: 0.70.3 => 0.70.3 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by satya164** [comment]
What command are you running to build the project?

**Comment by CJxD** [comment]
> What command are you running to build the project?

```
npx create-react-native-library@latest test \
    --slug "react-native-test" \
    --description "Test" \
    --author-name "Test" \
    --author-email "test@test.com" \
    --author-url "https://test.com" \
    --repo-url "https://github.com/test" \
    --languages kotlin-swift \
    --type module-turbo \
    --example native
```

**Comment by satya164** [comment]
That command creates the project. What command are you running to build the project?

**Comment by CJxD** [comment]
Sorry for the delay! I run `yarn` followed by `yarn build`.

**Comment by satya164** [comment]
The android project is built by running `yarn example android` - which will generate the codegen files, build the android code and run the app.

**Comment by sawa-ko** [comment]
I have the same issue...

```
// generated package.json

{
  "name": "@scl/react-native-scanner-manager",
  "version": "0.0.0",
  "description": "Use scanner from Zebra/Urovo devices.",
  "main": "src/index",
  "codegenConfig": {
    "name": "RNReactNativeScannerManagerSpec",
    "type": "modules",
    "jsSrcsDir": "src"
  },
  "author": " <> ()",
  "license": "UNLICENSED",
  "homepage": "#readme",
  "create-react-native-library": {
    "type": "turbo-module",
    "languages": "kotlin-objc",
    "version": "0.48.2"
  }
}

```

**Comment by atlj** [comment]
@sawa-ko could you create a new issue with a reproducible example? Could you post the full error message there?
