### ISSUE TITLE
Add new swift file not in scope

### ISSUE THREAD

**Issue by karimsaad687** [callstack/react-native-builder-bob#328]
### Description

Hello
I have a problem when create project with create-react-native-library
I keep find this error when create new swift file
File not found in scope

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

Create-react-native-library

### Environment

Mac osx 10.15
React native 0.70

**Comment by satya164** [comment]
Can you provide more details such as repro steps and exact error message?
