### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'project-path/npm-module-name/example/package.json'

### ISSUE THREAD

**Issue by liyamahendra** [callstack/react-native-builder-bob#336]
### Description

I saw a similar issue which is closed where it was suggested to run
```
npx create-react-native-library@latest react-native-awesome-library
```
and this seems to work just fine. But when I change `react-native-awesome-library` to some different name, say `react-native-hello-world`, I get the error saying:

```
Error: ENOENT: no such file or directory, open 'project-path/npm-module-name/example/package.json'
```

I'm attaching a screen recording of this 

https://user-images.githubusercontent.com/911879/204281446-ea4c399b-e6eb-4c2f-aefa-12ffebf97fa5.mp4

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

I executed the below command:

```
npx create-react-native-library@latest react-native-hello-world
```

### Environment

My Module wasn't created. Below are the details about the environment:

Node: v19.1.0
NPM: v9.1.2
MacOS: 12.16.1

Do let me know if you need any particular details

**Comment by satya164** [comment]
The error is because `HelloWorld` is a reserved name in React Native CLI. Any other name should work. We should be showing a proper error, however.
