### ISSUE TITLE
Getting NaN on running the example project

### ISSUE THREAD

**Issue by sshivaditya2019** [callstack/react-native-builder-bob#343]
### Description

I used the create-react-native-library to create a library, with the library being the "Native module" and the language being  "C++".   When I executed `yarn` followed by `yarn example android`, I got NaN value. I have made no changes to the default project.

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

What type of library do you want to develop? › Native module
Which languages do you want to use? › C++ for Android & iOS

### Environment

System:
    OS: Linux 5.15 undefined
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 2.36 GB / 15.55 GB
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: AI-212.5712.43.2112.8815526
  Languages:
    Java: 17.0.5 - /home/sshivaditya/.sdkman/candidates/java/current/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.1.0 => 18.1.0
    react-native: 0.70.6 => 0.70.6
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by BubbleTrouble14** [comment]
Have the same issue, with newArch and old way as well.

**Comment by ndangnguyen** [comment]
![telegram-cloud-photo-size-5-6129405020362356238-y](https://github.com/callstack/react-native-builder-bob/assets/31484530/748988f2-a03f-43a9-9baf-78ced3ff128c)
Change jint to jdouble
