### ISSUE TITLE
build.gradle issue when opening Android part of a module created by npx create-react-native-library react-native-awesome-module

### ISSUE THREAD

**Issue by Productivix** [callstack/react-native-builder-bob#347]
### Description

easy to reproduce : 
I just follow the doc from https://reactnative.dev/docs/native-modules-setup
npx create-react-native-library react-native-awesome-module
then I open with Android Studio the Android part of the react-native-awesome-module
and I get the fatal error for me : 
```
Build file '/mymodules/react-native-awesome-module/android/build.gradle' line: 118

A problem occurred evaluating root project 'android'.
> android: unable to locate React Native android sources. Ensure you have you installed React Native as a dependency in your project and try again.
```
So I cannot debug my module as described in https://reactnative.dev/docs/native-modules-android#setup

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

none

### Environment

$ npx react-native info
error Failed to load configuration of your project.

**Comment by piccinnigius** [comment]
@Productivix any update?

**Comment by Productivix** [comment]
no but I do not use anymore that lib at the end, I just develop in a normal RN stack that enable the Android Studio use.
Then you copy the Android part inside if you want to make a module but you cannot debug anymore.

**Comment by Productivix** [comment]
Yes you are right, we can develop on Android Studio on example part  . But do you mean that we have to develop and make the java module work on example/android part and then copy the job on the /android part of the lib before deploying it ?

**Comment by satya164** [comment]
> and then copy the job on the /android part of the lib before deploying it

What job?

You make your changes in the `android` folder at the root and test those changes using the example app. There's nothing additional to do before publishing. See the `CONTRIBUTING.md` in your project which describes the development workflow.

**Comment by atlj** [comment]
> Yes you are right, we can develop on Android Studio on example part  . But do you mean that we have to develop and make the java module work on example/android part and then copy the job on the /android part of the lib before deploying it ? 

There is no need for copying. If you make changes while you are working on the example/android, The files inside /android will also be changed. You can check the git to make sure.

**Comment by Productivix** [comment]
oh I will test , but I certainly missed to read an important page : where is that explained please ?

**Comment by atlj** [comment]
> oh I will test , but I certainly missed to read an important page : where is that explained please ?

I'm not sure if this is documented anywhere, but this is the general workflow we use while developing Native Modules.

**Comment by satya164** [comment]
> where is that explained please

See the `CONTRIBUTING.md` in your repo like I mentioned.

**Comment by Productivix** [comment]
hi, I read it and found : 
`
While developing, you can run the [example app](/example/) to test your changes. Any changes you make in your library's JavaScript code will be reflected in the example app without a rebuild. If you change any native code, then you'll need to rebuild the example app.`

So if I understand well : I have to develop in the library in "blind" (no assistance in typing java) and test in example on Android Studio ?

**Comment by atlj** [comment]
no please don't develop blindly 😄. Just open the example app on android studio > navigate to android > expand the app > find your module and code your stuff. Any changes here will be reflected to your code. This goes same for iOS. Open the example app on Xcode > expand the Pods > expand the development pods. Any changes here will also reflect. (Creating/removing/renaming/moving files themselves can be buggy this way so its the best to open the modules project directly on Xcode when you add/remove files or rename them.)

**Comment by Productivix** [comment]
hi, thank you ! 
so the doc in CONTRIBUTING.md says the reverse (or I understand the reverse) : may be someone needs to change the CONTRIBUTING.md explanations !

**Comment by atlj** [comment]
> hi, thank you !

Awesome everything worked out for you 🚀

> may be someone needs to change the CONTRIBUTING.md explanations !

We are welcoming new PRs if you are interested

**Comment by The-Pascal** [comment]
Hi, I also have similar confusion, what I am trying to achieve is - 

> I want to change some kotlin native code in the android module of the library (not the example app)

but while building the android module in android studio it's showing missing dependency for react-native (unresolved references for facebook)

[Here ](https://github.com/callstack/react-native-builder-bob/issues/347#issuecomment-1409477105) you mentioned to open example project and code in that, but I want to change the native library android code for library not the example project.

Please suggest for the same. Thanks

**Comment by Productivix** [comment]
I tested yet this lib , it works well now. develop the lib and test in example, the whole project being loaded in Android Studio.
