### ISSUE TITLE
Turbomodule with backward compatibility is not configured correctly

### ISSUE THREAD

**Issue by jpudysz** [callstack/react-native-builder-bob#352]
### Description

Hello callstack team!
I tried to use your library generator, and you did a great job. It supports React Native 0.71 with no additional config.

I used it to build my new library with backward compatibility. It worked great for iOS's new and old architecture, as well as for Android's new architecture.

For Android's old architecture, my module was not registered correctly. I was unable to call it via `NativeModules`. 

After the debug session, I've found that `android/src/oldarch/AwesomeLibrarySpec.kt` is missing one of the classes. I think we need to implement one more class called: `ReactModuleWithSpec`.

Here is the correct declaration:

```kotlin
abstract class AwesomeLibrarySpec internal constructor(context: ReactApplicationContext) : ReactContextBaseJavaModule(context), ReactModuleWithSpec {
  abstract fun multiply(a: Double, b: Double, promise: Promise)
}
```

Here is a diff from my lib that resolved the issue. You can fork my library before this commit and check out the issue: https://github.com/jpudysz/react-native-is-maestro/commit/ffd7b80f1687c262801e9c1ec40d604b9db25200#diff-975997629e741ea87e99a0694abde9f73dca9176d6f79b2664e68862316ae7f0R8

I hope it will help to make bob better generator 🏗️ 

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

- Turbo mobule with backward compat
- Kotlin & Objective-C

### Link to repro

https://github.com/jpudysz/react-native-is-maestro

### Environment

Node 16.16.0
React Native 0.71

**Comment by atlj** [comment]
Hey, I've gone through the repro link and found the issue. Spec files on Android shouldn't include any concrete implementation and have only abstract methods. This was the issue rather than missing interfaces. You can check this PR I've opened to see what was going wrong https://github.com/jpudysz/react-native-is-maestro/pull/1

**Comment by jpudysz** [comment]
@atlj thank you for the explanation. I didn't know about it!

**Comment by atlj** [comment]
You are welcome ^^ hope this fixes your issues 🥳
