### ISSUE TITLE
Prototype Pollution in JSON5 via Parse Method

### ISSUE THREAD

**Issue by Productivix** [callstack/react-native-builder-bob#366]
### Description

I wrote a module in KT with your explanations : very easy , thank you.
I publised on github and get by robot the issue  with 7.1/10 severity
see pdf attached (module is still private)
[Prototype Pollution in JSON5 via Parse Method · Dependabot alert #1 · Productivix_module_datalogicsdk-kt.pdf](https://github.com/callstack/react-native-builder-bob/files/10868465/Prototype.Pollution.in.JSON5.via.Parse.Method.Dependabot.alert.1.Productivix_module_datalogicsdk-kt.pdf)

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Objective-C
✔ Project created successfully at module_datalogicsdk!

### Environment

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 3.75 GB / 7.66 GB
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 18.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3

**Comment by satya164** [comment]
We're parsing your tsconfig.json with JSON5. If there's `__proto__` in your `tsconfig.json` then it's an issue in your tsconfig. From a vulnerability point of view, this is a pointless alert with this use case.

**Comment by Productivix** [comment]
hi, thanks , I thought it was important. no there no "proto" in my  tsconfig.json - sorry .
