### ISSUE TITLE
Expo Go immediately quits when running the example

### ISSUE THREAD

**Issue by jonasmerlin** [callstack/react-native-builder-bob#367]
### Description

On a freshly initialized project, running `yarn` and then `yarn example ios` brings up the simulator, installs and opens the Expo Go app, but then immediatly quits the app while showing the (Expo) splash screen. No error is printed anywhere as far as I can tell.

### Packages

- [X] create-react-native-library
- [X] react-native-builder-bob

### Selected options

The ones that come with running `npx create-react-native-library@latest awesome-library` and then selecting `JavaScript library`

### Environment

```
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.64 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - ~/.config/nvm/versions/node/v19.6.0/bin/node
    Yarn: 1.22.19 - ~/.config/nvm/versions/node/v19.6.0/bin/yarn
    npm: 9.4.1 - ~/.config/nvm/versions/node/v19.6.0/bin/npm
    Watchman: 2023.02.27.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/jonasmerlin/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.3 => 0.71.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by atlj** [comment]
Hey, could you check it in the latest version again? I was not able to reproduce it.

**Comment by atlj** [comment]
Could you try using Node v16.xx LTS, it could be the reason for a potential crash.

**Comment by enestatli** [comment]
> Could you try using Node v16.xx LTS, it could be the reason for a potential crash.

try on v16.20.0, same crash
