### ISSUE TITLE
Error when creating a package. Error in step `Copying template`

### ISSUE THREAD

**Issue by guillempuche** [callstack/react-native-builder-bob#382]
### Description

The first time I try this repo.

When running `npx create-react-native-library@latest name` and fill all the `package.json` data, this happens:
![imatge](https://user-images.githubusercontent.com/3519924/233651503-b47c9e67-6c64-4209-ae63-7f415d15f020.png)

```bash
/Users/aaaa/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/generateExampleApp.js:62
        reject(new Error(stderr));
               ^

Error: - Downloading template
✔ Downloading template
- Copying template
✖ Copying template
error Error: Couldn't find the "/var/folders/ys/spt316fs5sxck01gjy40s1rc0000gn/T/rncli-init-template-AoLPqU/node_modules/react-native/template.config.js file inside "react-native" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template.

    at ChildProcess.<anonymous> (/Users/aaaa/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/generateExampleApp.js:62:16)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12
```

The line 62 of `generateExampleApp.js` in the npx's cache `~/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils`

```js
        reject(new Error(stderr));
```

I tried version `0.27.2`. The same problem.

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

The step `What type of library do you want to develop?` I tried all, only `Javascript` worked.

### Environment

- macOS 13
- Node 16.15.1

**Comment by dvlkv** [comment]
+1
