### ISSUE TITLE
Update Android template to have a `namespace` declaration

### ISSUE THREAD

**Issue by cortinico** [callstack/react-native-builder-bob#394]
### Description

See this issue for the full report on why this is needed:
- https://github.com/react-native-community/discussions-and-proposals/issues/671

Let's update bob whenever is possible so that libraries organically get this change out.

### Packages

- [ ] create-react-native-library
- [X] react-native-builder-bob

### Selected options

See above.

### Link to repro

https://github.com/react-native-community/discussions-and-proposals/issues/671

### Environment

See above.

**Comment by atlj** [comment]
Should we add an if statement to check the React Native version and apply it only if it's 0.73 or newer than 0.73, or is it safe to apply unconditionally? Would this work on React Native 0.72? If we are not sure I can test it before committing.

**Comment by cortinico** [comment]
Nope it can't be added unconditionally. It should be applied only for 0.71+
