### ISSUE TITLE
not able to generate library

### ISSUE THREAD

**Issue by hariomsharma-nag** [callstack/react-native-builder-bob#400]
### Description

Hello,

 I am getting error while creating react native library. 

npx create-react-native-library@latest awesome-library

It is giving error while generate example - 

npx create-react-native-library@latest awesome-library
npx: installed 96 in 2.782s
✔ What is the name of the npm package? … react-native-awesome-library
✔ What is the description for the package? … des
✔ What is the name of package author? … <name>
✔ What is the email address for the package author? … <email>
✔ What is the URL for the package author? … <url>
✔ What is the URL for the repository? …<url>
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Objective-C
⠼ Generating example

npx: installed 532 in 16.43s
error Failed to load configuration of your project.

(node:71292) UnhandledPromiseRejectionWarning: Error: npx: installed 532 in 16.43s
error Failed to load configuration of your project.

    at ChildProcess.<anonymous> (/Users/hh/.npm/_npx/71292/lib/node_modules/create-react-native-library/lib/utils/generateExampleApp.js:62:16)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:71292) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:71292) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I tried on 3 node versions. 
v14, v16, v19 but same error on each.

Thank you!

### Packages

- [X] create-react-native-library
- [x] react-native-builder-bob

### Selected options

npx create-react-native-library@latest awesome-library
npx: installed 96 in 2.782s
✔ What is the name of the npm package? … react-native-awesome-library
✔ What is the description for the package? … des
✔ What is the name of package author? … <name>
✔ What is the email address for the package author? … <email>
✔ What is the URL for the package author? … <url>
✔ What is the URL for the repository? …<url>
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Objective-C
⠼ Generating example

### Environment

MacOS - v13.3.1 (a) 
Node - 14, 16, 19 (same error on each)

**Comment by romil-soni** [comment]
Was facing the same problem seems to have been fixed now.

I suspect some sort of backward compatibility thing with the react native cli had been broken.

**Comment by satya164** [comment]
Closing since looks like it's fixed in CLI.
