### ISSUE TITLE
Update dependency in a template

### ISSUE THREAD

**Issue by birdofpreyru** [callstack/react-native-builder-bob#432]
### Description
https://github.com/callstack/react-native-builder-bob/blob/6650bc170b3c872ad290965856162334c8394df6/packages/create-react-native-library/templates/common/%24package.json#L63
should become (since RN v0.72)
```
"@react-native/eslint-config": "^0.72.2",
```
and, ESLint config should be updated accordingly.

Also
`    "@types/react-native": "0.70.0",` should be dropped.

Also, versions of other dependencies might be bumped up.

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

N/A

### Environment

N/A

**Comment by atlj** [comment]
`"@react-native-community/eslint-config": "^3.0.2", ` -> `"@react-native/eslint-config": "^0.72.2",` was done with #452. Please take a look at the changes and update the other dependencies if needed.

**Comment by birdofpreyru** [comment]
Heads up: I'm on it, will PR within a few days.
