### ISSUE TITLE
When create a new module version com.facebook.react:react-native+	not work

### ISSUE THREAD

**Issue by Andersonfrfilho** [callstack/react-native-builder-bob#446]
### Description

When a create a new project, using command:  `npx create-react-native-library react-name-module`
and open project in android studio occour error in get module: com.facebook.react:react-native+,
I try version latest `0.71.0-rc.0` but not work, so try version `0.20.1` 
to work for me, 
this is valid to be corrected ? 

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

Need to install the following packages:
  create-react-native-library@0.31.1
Ok to proceed? (y) y
√ What is the name of the npm package? ... react-native-sunshine-android
√ What is the description for the package? ... module test chatbot sunshine
√ What is the name of package author? ... Anderson Fernandes
√ What is the email address for the package author? ... andersonfrfilho@gmail.com
√ What is the URL for the package author? ... https://github.com/Andersonfrfilho
√ What is the URL for the repository? ... https://github.com/Andersonfrfilho/react-native-sunshine-android
√ What type of library do you want to develop? » Native module

### Environment

info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Memory: 4.03 GB / 15.80 GB
Binaries:
  Node:
    version: 18.17.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn: Not Found
  npm:
    version: 9.6.7
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-223.8836.35.2231.10406996
  Visual Studio: Not Found
Languages:
  Java: 11.0.20
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by atlj** [comment]
Hey, could you provide more details about the steps you took?

Which project have you opened on Android Studio?
What is the full error?
Seems like the steps are not too specific, so could you provide a reproducible repository?

**Comment by blabno** [comment]
I'm also having this issue. When you generate the plugin project structure with `create-react-native-library` and open `android` folder in Android Studio then it tries to sync gradle project and ends up with the error

> Failed to resolve: com.facebook.react:react-native:+

![image](https://github.com/callstack/react-native-builder-bob/assets/431064/520b121e-2593-489f-95af-017630dfc150)

Also as you can notice no react native class is detected by AndroidStudio:

```
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.module.annotations.ReactModule;
```
 
All of the above imports are in red.

**Comment by atlj** [comment]
Hey @blabno, could you try to open `example/android` instead of `/android` on Android Studio? You can see the `CONTRIBUTING.md` that's generated with your project for details.

**Comment by blabno** [comment]
@atlj Interesting, I would never guess that in order to develop the plugin I have to open the example/android, but it works.
Thank you.

**Comment by atlj** [comment]
@Andersonfrfilho, assuming [my older comment](https://github.com/callstack/react-native-builder-bob/issues/446#issuecomment-1693286487) would fix your problem, I'm closing this issue. Please reopen it if it doesn't work for you.
