### ISSUE TITLE
[New Architecture][Android][Windows] React Native Codegen is unable to locate the "src" folder.

### ISSUE THREAD

**Issue by alabsi91** [callstack/react-native-builder-bob#453]
### Description

While building for React Native's new architecture on Windows, an issue arises where the codegen cannot locate the "src" folder. This leads to an empty path at "android\build\generated\source\codegen\java," causing the build to fail. To address this, I managed to resolve the problem by making the following changes:

```diff
// ./package.json

"codegenConfig": {
    "name": "RNMaterialYouSpec",
    "type": "modules",
-  "jsSrcsDir": "src",
+  "jsSrcsDir": "",
}
```
### Packages

- [ ] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

I tested it by creating new empty projects for both TurboModules and Fabric (using both Java and Kotlin), and unfortunately, the build process failed for both. However, the build succeeded for Paper with the old architecture.

### Environment

Windows 11
Node.js v18.16.0
npm

**Comment by satya164** [comment]
Can you provide a link to the project with the issue?

**Comment by alabsi91** [comment]
The issue was resolved when using the latest template version. Thank you.
