### ISSUE TITLE
cosmiconfig@8.3.2: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by little-buddy** [callstack/react-native-builder-bob#455]
### Description

Can't install devDependencies ! ! !

<img width="713" alt="image" src="https://github.com/callstack/react-native-builder-bob/assets/30054881/c1555709-6ea2-4532-a33c-836c42107e20">

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

Only 
```JS
npx create-react-native-library@latest awesome-library

yarn install
```

### Environment

create-react-native-library@0.31.1  

local node@16.20.2

**Comment by little-buddy** [comment]
I think you should change the node version requirements in the template

**Comment by atlj** [comment]
Hey, NodeJs 16 LTS is coming to it's end of life on September 11th [source](https://nodejs.org/en/blog/announcements/nodejs16-eol). For this reason, we wouldn't like to support it.

**Comment by little-buddy** [comment]
I found that the version is incompatible because yarn.lock is missing. 
Maybe yarn.lock should be retained in the template 😄
