### ISSUE TITLE
latest 0.34.1 fails to create a Native module on Linux : blocking

### ISSUE THREAD

**Issue by Productivix** [callstack/react-native-builder-bob#480]
### Description

I wanted to create a react-native module as usual, 
$ npx create-react-native-library@latest module_mlkit_barcode-scanning
Need to install the following packages:
create-react-native-library@0.34.1
Ok to proceed? (y) y
...
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Java & Objective-C
⠏ Generating example app

then I got the following errors  : 
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
- Downloading template
✔ Downloading template
- Copying template
/home/william/.npm/_npx/dea611a43221eddd/node_modules/graceful-fs/polyfills.js:265
        if (!chownErOk(er)) throw er
                            ^

Error: ENOENT: no such file or directory, chmod '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/modules/module_mlkit_barcode-scanning/example/android/gradlew'
    at Object.chmodSync (node:fs:1991:3)
    at Object.chmodSync (/home/william/.npm/_npx/dea611a43221eddd/node_modules/graceful-fs/polyfills.js:263:21)
    at ReadStream.<anonymous> (/home/william/.npm/_npx/dea611a43221eddd/node_modules/@react-native-community/cli/build/tools/copyFiles.js:83:19)
    at ReadStream.emit (node:events:517:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/modules/module_mlkit_barcode-scanning/example/android/gradlew'
}

Node.js v18.18.0
/home/william/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/spawn.js:27
        reject(new Error(stderr.trim()));
               ^

Error: npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
- Downloading template
✔ Downloading template
- Copying template
/home/william/.npm/_npx/dea611a43221eddd/node_modules/graceful-fs/polyfills.js:265
        if (!chownErOk(er)) throw er
                            ^

Error: ENOENT: no such file or directory, chmod '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/modules/module_mlkit_barcode-scanning/example/android/gradlew'
    at Object.chmodSync (node:fs:1991:3)
    at Object.chmodSync (/home/william/.npm/_npx/dea611a43221eddd/node_modules/graceful-fs/polyfills.js:263:21)
    at ReadStream.<anonymous> (/home/william/.npm/_npx/dea611a43221eddd/node_modules/@react-native-community/cli/build/tools/copyFiles.js:83:19)
    at ReadStream.emit (node:events:517:28)
    at emitCloseNT (node:internal/streams/destroy:132:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/home/william/logiciels/logiciels-windows/dev_RN-Node-GIT/modules/module_mlkit_barcode-scanning/example/android/gradlew'
}

Node.js v18.18.0
    at ChildProcess.<anonymous> (/home/william/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/spawn.js:27:16)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)

Node.js v18.18.0

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Java & Objective-C

### Environment

Fetching system and libraries information...
System:
  OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
  CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Memory: 51.78 GB / 62.62 GB
  Shell:
    version: 5.2.15
    path: /bin/bash
Binaries:
  Node:
    version: 18.18.0
    path: /usr/local/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 10.1.0
    path: /usr/local/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by satya164** [comment]
This is a bug in CLI. Unfortunately we cannot do anything on our side. It'll be fixed when this is released: https://github.com/react-native-community/cli/pull/2096

**Comment by Productivix** [comment]
thank you , my only solution is to start a project on Windows, clone on GitHub and clone the repo on Linux ....long.
