### ISSUE TITLE
React Native Vector Icon is Not working

### ISSUE THREAD

**Issue by itsaladin** [callstack/react-native-builder-bob#490]
### Description

Unable to resolve "@expo/vector-icons/FontAwesome" from "..\src\index.tsx"

I just installed #react native vector icon in my desired project. I'm fetching `Unable to resolve "@expo/vector-icons/FontAwesome" from "..\src\index.tsx" .  `

I'm feeling like a rock start. before I had made three npm package by #react-native-builder-bob

![desktop](https://github.com/callstack/react-native-builder-bob/assets/37948276/aef096f1-f662-4f34-881f-0e2ea8c30cde)

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

Before I made the NPM package but I couldn't setup any external configuration.

### Environment

System:
  OS: Windows 10 10.0.19045
  CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
  Memory: 3.22 GB / 15.83 GB

Binaries:
  Node:
    version: 18.17.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 3.6.1
    path: ~\AppData\Roaming\npm\yarn.CMD
  npm:
    version: 10.2.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found

SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: AI-223.8836.35.2231.10406996
  Visual Studio:
    - 17.6.33829.357 (Visual Studio Professional 2022)
Languages:
 
 Java:
    version: 11.0.20
    path: /c/Program Files/Common Files/Oracle/Java/javapath/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  
react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by satya164** [comment]
Do you have `@expo/vector-icons` installed?
