### ISSUE TITLE
npm pack issue

### ISSUE THREAD

**Issue by ponrajasekar** [callstack/react-native-builder-bob#511]
### Description

![Capture](https://github.com/callstack/react-native-builder-bob/assets/6649593/2fa23cf8-59b8-47c0-98cd-37b1aae0d9a5)

### Packages

- [ ] create-react-native-library
- [X] react-native-builder-bob

### Selected options

npm ERR! code 1
npm ERR! path D:\React\react-native-awesome-library
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c bob build
npm ERR! node:fs:581
npm ERR!   return binding.open(
npm ERR!                  ^
npm ERR!
npm ERR! Error: ENOENT: no such file or directory, open 'D:\C:\Users\ponrajasekart\AppData\Roaming\npm\node_modules\bob\conf\commands.json'
npm ERR!     at Object.openSync (node:fs:581:18)
npm ERR!     at Object.readFileSync (node:fs:457:35)
npm ERR!     at Object.exec (file:///C:/Users/ponrajasekart/AppData/Roaming/npm/node_modules/bob/lib/cli.js:53:42)
npm ERR!     at file:///C:/Users/ponrajasekart/AppData/Roaming/npm/node_modules/bob/bin/bob.js:4:5
npm ERR!     at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
npm ERR!     at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
npm ERR!     at async loadESM (node:internal/process/esm_loader:28:7)
npm ERR!     at async handleMainPromise (node:internal/modules/run_main:120:12) {
npm ERR!   errno: -4058,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'open',
npm ERR!   path: 'D:\\C:\\Users\\ponrajasekart\\AppData\\Roaming\\npm\\node_modules\\bob\\conf\\commands.json'
npm ERR! }
npm ERR!
npm ERR! Node.js v21.5.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ponrajasekart\AppData\Local\npm-cache\_logs\2023-12-27T09_06_40_393Z-debug-0.log

### Link to repro

https://medium.com/simform-engineering/create-and-publish-react-native-package-d89c68b3ccc0

### Environment

![Capture](https://github.com/callstack/react-native-builder-bob/assets/6649593/7e16a37b-fe10-4dc2-84f0-2ec767d8b1ea)

**Comment by EliasB23** [comment]
Did you find a solution for this?

**Comment by atlj** [comment]
This seems like a Windows issue. We haven't been testing our changes against Windows and Windows compatibility isn't a goal of ours right now. I'd suggest using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install). Sorry for the inconvenience.
