### ISSUE TITLE
Error during build-ios workflow action

### ISSUE THREAD

**Issue by mattiaferrari02** [callstack/react-native-builder-bob#528]
### Description

I'm running the github action to build the ios app, but the action fails because hermes can't find node. 
I had the .xcode.env.local committed and gave an error.
Then i gitignored it but the error presisted. from the log i can see that the error is located here
/Users/runner/Library/Developer/Xcode/DerivedData/MyApp-fdppxdaabfbsnhbrtydartoiatka/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/hermes-engine.build/Script-46EB2E00015D40.sh: line 9: /private/var/folders/qv/pdh5wsgn0lq3dp77zj602b5c0000gn/T/xfs-d0d113ba/node: No such file or directory

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

> turbo module
> c++ for android an ios

### Link to repro

https://github.com/mattiaferrari02/react-native-test-module

### Environment

The problem is on the action so i don't think that my environment matters but ok

System:
  OS: macOS 12.6.8
  CPU: (8) arm64 Apple M1
  Memory: 158.95 MB / 16.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v18.19.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2023.03.13.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.2
      - iOS 16.2
      - macOS 13.1
      - tvOS 16.1
      - watchOS 9.1
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 28.0.3
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
      - 34.0.0
    System Images:
      - android-29 | Google Play ARM 64 v8a
      - android-31 | Google APIs ARM 64 v8a
      - android-31 | Google APIs Intel x86 Atom_64
      - android-31 | Google Play ARM 64 v8a
    Android NDK: 21.4.7075529
IDEs:
  Android Studio: Hedgehog 2023.1.1 Patch 2 Hedgehog 2023.1.1 Patch 2
  Xcode:
    version: 14.2/14C18
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 3.1.3
    path: /opt/homebrew/opt/ruby@3.1/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by satya164** [comment]
Try making this change in your project https://github.com/callstack/react-native-builder-bob/commit/5217411632505b40b01b7dbee39c888eccb81639
