### ISSUE TITLE
Error when trying to run on ios

### ISSUE THREAD

**Issue by Dougsrodrigues** [callstack/react-native-builder-bob#529]
### Description

After run `npx create-react-native-library@latest` and try run `yarn example ios` i receive this error bellow

error Failed to build iOS project. "xcodebuild" exited with error code '65'. To debug build logs further, consider building your app with Xcode.app, by opening 'LocalStorageSantiagoExample.xcodeproj'.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -project LocalStorageSantiagoExample.xcodeproj -configuration Debug -scheme LocalStorageSantiagoExample -destination id=00008120-001C39091E6BC01E

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

Prepare packages

ComputeTargetDependencyGraph
note: Building targets in dependency order
note: Target dependency graph (1 target)
    Target 'LocalStorageSantiagoExample' in project 'LocalStorageSantiagoExample' (no dependencies)

GatherProvisioningInputs

CreateBuildDescription

/Users/douglassantiago/projetos/projetin-rn-entrevistas/local-storage-santiago/example/ios/Pods/Target Support Files/Pods-LocalStorageSantiagoExample/Pods-LocalStorageSantiagoExample.debug.xcconfig:1:1: error: unable to open configuration settings file
error: Unable to load contents of file list: '/Target Support Files/Pods-LocalStorageSantiagoExample/Pods-LocalStorageSantiagoExample-frameworks-Debug-input-files.xcfilelist' (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
error: Unable to load contents of file list: '/Target Support Files/Pods-LocalStorageSantiagoExample/Pods-LocalStorageSantiagoExample-frameworks-Debug-output-files.xcfilelist' (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
error: Unable to load contents of file list: '/Target Support Files/Pods-LocalStorageSantiagoExample/Pods-LocalStorageSantiagoExample-resources-Debug-input-files.xcfilelist' (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
error: Unable to load contents of file list: '/Target Support Files/Pods-LocalStorageSantiagoExample/Pods-LocalStorageSantiagoExample-resources-Debug-output-files.xcfilelist' (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
warning: Run script build phase '[CP] Copy Pods Resources' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
warning: Run script build phase '[CP] Embed Pods Frameworks' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-LocalStorageSantiagoExample/Pods-LocalStorageSantiagoExample-frameworks-Debug-output-files.xcfilelist' (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')
warning: Unable to read contents of XCFileList '/Target Support Files/Pods-LocalStorageSantiagoExample/Pods-LocalStorageSantiagoExample-resources-Debug-output-files.xcfilelist' (in target 'LocalStorageSantiagoExample' from project 'LocalStorageSantiagoExample')

** BUILD FAILED **

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

N/A

### Link to repro

https://github.com/Dougsrodrigues/react-native-local-storage-santiago

### Environment

System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M2 Pro
  Memory: 113.30 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.19.0
    path: ~/.nvm/versions/node/v18.19.0/bin/node
  Yarn:
    version: 3.6.1
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v18.19.0/bin/npm
  Watchman:
    version: 2023.07.03.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "31"
      - "33"
      - "34"
    Build Tools:
      - 30.0.3
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 34.0.0
    System Images:
      - android-33 | Google APIs ARM 64 v8a
      - android-33 | Google Play ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-34 | Google Play ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.9971841
  Xcode:
    version: 15.1/15C65
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.10
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.4
    wanted: 0.73.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by inarol** [comment]
@Dougsrodrigues Hi, here is a solution and it works for me. You can try the following commands. 
```bash
$ cd example
$ bundle install
$ cd ios
$ pod install
```

**Comment by atlj** [comment]
Hey there, the `bundle install` command as mentioned by @narol1024 should fix the issue. Closing this.
