### ISSUE TITLE
No Xcode project in native module library

### ISSUE THREAD

**Issue by harry-anderson** [callstack/react-native-builder-bob#535]
### Description

Hi I am trying to bootstrap a new native module library using your tool. No xcode project is generated. I expect to find xcode project in the `ios` directory I can open to work on my native module. What am I doing wrong here? Thanks

```bash
harry@mm scratch % npx create-react-native-library@latest test-lib
...
harry@mm scratch % cd test-lib/ios
harry@mm ios % ls
TestLib-Bridging-Header.h	TestLib.mm			TestLib.swift
```

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

✔ What is the name of the npm package? … react-native-test-lib
✔ What is the description for the package? … a test
✔ What is the name of package author? … Harry Anderson
✔ What is the email address for the package author? … harry@nuggets.life
✔ What is the URL for the package author? … https://github.com/harry-anderson
✔ What is the URL for the repository? … https://github.com/harry-anderson/react-native-test-lib
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Swift
✔ Project created successfully at test-lib!

### Link to repro

https://github.com/harry-anderson/test-lib

### Environment

System:
  OS: macOS 14.2
  CPU: (10) arm64 Apple M2 Pro
  Memory: 856.78 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.0
    path: ~/Library/Caches/fnm_multishells/602_1709172487759/bin/node
  Yarn:
    version: 3.6.1
    path: ~/Library/Caches/fnm_multishells/602_1709172487759/bin/yarn
  npm:
    version: 10.1.0
    path: ~/Library/Caches/fnm_multishells/602_1709172487759/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.14.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    Android NDK: 25.1.8937393
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11076708
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by harry-anderson** [comment]
See react native documentation for [iOS native modules](https://reactnative.dev/docs/native-modules-ios#setup):
> To get started, open up the iOS project within your React Native application in Xcode. You can find your iOS project here within a React Native app:

**Comment by harry-anderson** [comment]
I saw discussion #505 however It doesn't solve my issue

**Comment by rakesho-vel** [comment]
@harry-anderson did it resolve for you?

**Comment by gwashburne** [comment]
@harry-anderson How did you resolve this? I'm having the same issue
