### ISSUE TITLE
Cannot install a Android library which is deployed in Github Packages.

### ISSUE THREAD

**Issue by siva-optim** [callstack/react-native-builder-bob#540]
### Description

I have published my android library with access control.

I tried to install it in a sample React Native CLI project it is working fine.

But i tried to install the same android library in "create-react-native-library" project. 

I am getting the below error

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.<Library Name>.android:sdk:0.0.4.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/<Library Name>/android/sdk/0.0.4/sdk-0.0.4.pom
       - https://repo.maven.apache.org/maven2/com/<Library Name>/android/sdk/0.0.4/sdk-0.0.4.pom
       - file:/Users/<developer name>/<organization name>/<Library Name>-react-native/example/node_modules/jsc-android/dist/com/<Library Name>/android/sdk/0.0.4/sdk-0.0.4.pom
       - https://dl.google.com/dl/android/maven2/com/<Library Name>/android/sdk/0.0.4/sdk-0.0.4.pom
       - https://www.jitpack.io/com/<Library Name>/android/sdk/0.0.4/sdk-0.0.4.pom
     Required by:
         project :app > project :<Library Name>-react-native

Steps I have done:

Added below code to ./android/build.gradle file in 
repositories {
mavenCentral()
 ++  maven {
  ++    url = uri("https://maven.pkg.github.com/OWNER/REPOSITORY")
  ++   credentials {
  ++          username = "USERNAME"
  ++         password = "TOKEN"
  ++    }
   }
}
dependencies {
...
implementation('GROUP_ID:ARTIFACT_ID:VERSION')
}

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

Selected options:
- Project type: React Native Library (Kotlin & OBJC)
- Library deployment method: GitHub Packages
- Library version: 0.0.4
- Repository URL: https://maven.pkg.github.com/OWNER/REPOSITORY
- Repository credentials: Username: USERNAME, Token: TOKEN
- Gradle repository configuration:
  repositories {
mavenCentral()
maven {
url = uri("https://maven.pkg.github.com/OWNER/REPOSITORY")
credentials {
username = "USERNAME"
password = "TOKEN"
}
}
}

- Dependency declaration in `./android/build.gradle`:
dependencies {
...
implementation('GROUP_ID:ARTIFACT_ID:VERSION')
}

### Link to repro

Not Yet Published

### Environment

Environment:
- Operating System: macOS Sonoma 14.1
- IDE/Editor: Visual Studio Code
- Node.js version: v20.11.1
- React Native version:0.73.5
- Java Development Kit (JDK) version: openJDK 17
- Gradle version: 7.2

**Comment by satya164** [comment]
Repositories should be included in the app's `build.gradle` file, which means `example/android/app/build.gradle` for your repo and `android/app/build.gradle` for consumers.

**Comment by siva-optim** [comment]
> Repositories should be included in the app's `build.gradle` file, which means `example/android/app/build.gradle` for your repo and `android/app/build.gradle` for consumers.

May I ask why ?
And my requirement is to wrap up native android sdk with react native library for React Native support.

**Comment by satya164** [comment]
> > Repositories should be included in the app's `build.gradle` file, which means `example/android/app/build.gradle` for your repo and `android/app/build.gradle` for consumers.
> 
> 
> 
> May I ask why ?
> 
> And my requirement is to wrap up native android sdk with react native library for React Native support.

Because that's how it works on Android.

**Comment by siva-optim** [comment]
> > > Repositories should be included in the app's `build.gradle` file, which means `example/android/app/build.gradle` for your repo and `android/app/build.gradle` for consumers.
> > 
> > 
> > May I ask why ?
> > And my requirement is to wrap up native android sdk with react native library for React Native support.
> 
> Because that's how it works on Android.

Could you please provide a detailed answer.
what are the issues we will face if we add this feature i asked ?

**Comment by satya164** [comment]
> > > > Repositories should be included in the app's `build.gradle` file, which means `example/android/app/build.gradle` for your repo and `android/app/build.gradle` for consumers.
> 
> > > 
> 
> > > 
> 
> > > May I ask why ?
> 
> > > And my requirement is to wrap up native android sdk with react native library for React Native support.
> 
> > 
> 
> > Because that's how it works on Android.
> 
> 
> 
> Could you please provide a detailed answer.
> 
> what are the issues we will face if we add this feature i asked ?

Android uses Gradle build system. You need to do it how it works on Gradle on Android. We don't determine how it works. You'll need to ask Gradle developers to add this feature.
