### ISSUE TITLE
React Native Gradle Plugin Shouldn't only be for New Architecture

### ISSUE THREAD

**Issue by robertwt7** [callstack/react-native-builder-bob#547]
### Description

This line in the `build.gradle`

```

if (isNewArchitectureEnabled()) {
  apply plugin: "com.facebook.react"
}
```

At this point the gradle plugin also helps replacing `react-native` to `react-android` from mavenCentral. should this plugin also applies to app without new architecture? I fail to see why is this only needed for new architecture

sorry if this is a dumb report

### Packages

- [ ] create-react-native-library
- [X] react-native-builder-bob

### Selected options

https://github.com/callstack/react-native-builder-bob/blob/aa4d72367b6dae098cc38f10b04e19daf3499249/packages/create-react-native-library/templates/native-common/android/build.gradle#L30-L32

### Link to repro

https://github.com/callstack/react-native-builder-bob/blob/aa4d72367b6dae098cc38f10b04e19daf3499249/packages/create-react-native-library/templates/native-common/android/build.gradle#L30-L32

### Environment

React Native

**Comment by robertwt7** [comment]
yeah the plugin is supposed to do that, but the template is only installing the new architecture is enabled from the code here:
```
 if (isNewArchitectureEnabled()) { 
   apply plugin: "com.facebook.react" 
 } 
```

When I create new react native app, in the `build.gradle`, it installs the `com.facebook.react` anyway without any loop conditions

Try creating with this and see the build.gradle:
```
npx react-native@latest init AwesomeProject
```

**Comment by robertwt7** [comment]
The problem is that the template to create new module only installs the plugin on the new architecture while react native example on new projects installs it without any condition.

I'll try my module with the old architecture this week once i've finalised it. but shouldn't the template be the same with react native example? I'm not sure how better I can be at explaining the problem if you still can't see it. I can still try to reproduce it with the old architecture

**Comment by satya164** [comment]
Why should the library template be the same as example app? Library and apps are different things.

The templates are based on examples from Meta which adds the plugin conditionally.

If the current setup is working without any problems then I don't see why this is an issue. For this to be an issue it needs to be breaking something or causing problems.

**Comment by satya164** [comment]
https://github.com/react-native-community/RNNewArchitectureLibraries/blob/feat/back-turbomodule/example-library/android/build.gradle
