### ISSUE TITLE
Remove Typescript warnings and use cascading tsconfigs or cli switches instead

### ISSUE THREAD

**Issue by shamilovtim** [callstack/react-native-builder-bob#552]
### Problem

When various settings are specified in `tsconfig` the `prepare` command throws warnings:

```
⚠ Found following options in the config file which can conflict with the CLI options. Please remove them from tsconfig.json:
```

These warnings conflict with being able to properly use `tsc` in the project for type-checking and are a source of confusion for contributors and maintainers.

Example:

- Warning users not to use `noEmit` to make sure files are never accidentally emitted. Rather than do this the `prepare` script can either just pass `--noEmit false` or use its own tsconfig rather than rely on the user's tsconfig. Indeed because of the way bob handles compilation it **requires** noEmit to be true because the user cannot run `yarn tsc` and emit the same artifacts that bob does which is way more complex than `yarn tsc` can do on its own with one tsconfig. It doesn't make sense to warn users not to use noEmit when that's what they should be using.

### Desired functionality:
The build tool should use the cascading and extending of tsconfigs and/or cli switches to enforce its requirements rather than print warnings in the CLI. 

### Packages

- [X] create-react-native-library
- [X] react-native-builder-bob

### Selected options

N?A

### Link to repro

N/A

### Environment

N/A

**Comment by satya164** [comment]
> either just pass --noEmit false

It's not possible to pass `--noEmit` when using `--emitDeclarationOnly` which we need to be able to generate type declarations.

> or use its own tsconfig rather than rely on the user's tsconfig

This means user may have errors when compiling that don't show up in their editor or when running `tsc`. Which is not a good experience.

bob already supports specifying a different `tsconfig.json` file. You can create a different config file used for bob, and your own `tsconfig.json` can extend that and `noEmit` if you want.

**Comment by shamilovtim** [comment]
@satya164 

see my screengran. this has happened to me working on many `react-native-builder-bob` based packages. harmlessly run `yarn tsc` through simple muscle memory. end up with my directories polluted with dozens of files because bob's settings are not propagated to the underlying tsconfig file. bob compiles to /lib/common, lib/module/ and lib/typescript but does not reflect its configuration in the tsconfig, so the underlying tsconfig erroneously compiles a bunch of stuff and pollutes people's working state. there has to be a better way than this, which is why i opened my issue. one might argue "why didn't you run `yarn tsc --noEmit`" but I don't think it's fair to expect thousands of people to know that the tsconfig bob uses is outputting typescript differently from bob. 

<img width="465" alt="Screenshot 2024-05-10 at 12 13 38 PM" src="https://github.com/callstack/react-native-builder-bob/assets/3495974/75c3c005-a37d-4d5a-a110-b7a6d3e623ba">

**Comment by satya164** [comment]
PR welcome to override whatever options can be overridden.
