### ISSUE TITLE
Cannot open android project in android studio

### ISSUE THREAD

**Issue by GNUGradyn** [callstack/react-native-builder-bob#568]
### Description

Hello. Upon opening a freshly generated library project in android studio there are a couple issues. I created a library with the options specified in "Selected Options" and ran `yarn` in the new project. I then attempted to open the android folder within the new library in android studio to work on the native side of things. The first problem you'll encounter is this error when it tries to gradle sync
```
Could not create task ':generateDebugRFile'.
Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```
This is because the AGP version and gradle version are not paired. Go ahead and downgrade gradle to 7.3.3 to get past this. You can also upgrade both if you prefer that route but the result is the same.

Regardless which route you took to get here you will be looking at a screen like this when you open a java file
![image](https://github.com/callstack/react-native-builder-bob/assets/20762604/7a801a6a-7366-4c81-ba26-8becadb73ca2)
The IDE cannot find anything, even built in things like NonNull.

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

What is the name of the npm package? ... react-native-create-react-native-library-mre
√ What is the description for the package? ... demo for a bug
√ What is the name of package author? ... Gradyn Wursten
√ What is the email address for the package author? ... me@gradyn.com
√ What is the URL for the package author? ... https://github.com/GNUGradyn
√ What is the URL for the repository? ... https://github.com/GNUGradyn/react-native-create-react-native-library-mre
√ What type of library do you want to develop? » Native module
√ Which languages do you want to use? » Java & Swift

### Link to repro

https://github.com/GNUGradyn/react-native-create-react-native-library-mre

### Environment

System:
  OS: Windows 11 10.0.22631
  CPU: "(12) x64 AMD Ryzen 5 7600 6-Core Processor              "
  Memory: 13.22 GB / 31.15 GB
Binaries:
  Node:
    version: 20.13.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 3.6.1
    path: C:\Program Files\nodejs\yarn.CMD
  npm:
    version: 10.5.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK: Not Found
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.8.34511.84 (Visual Studio Community 2022)
Languages:
  Java:
    version: 17.0.11
    path: /c/Program Files/Common Files/Oracle/Java/javapath/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.2
    wanted: 0.74.2
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

It says the android SDK is not found but it is at `c:\Android\Sdk` which the IDE is aware of so ignore that bit

**Comment by satya164** [comment]
> I created a library with the options specified in "Selected Options" and ran yarn in the new project. I then attempted to open the android folder within the new library in android studio to work on the native side of things

As mentioned in the generated `CONTRIBUTING.md` in your project, you need to open the `example/android` folder in Android Studio.

**Comment by GNUGradyn** [comment]
Thanks. Might want to make some mention of this in this repos readme, or at least some mention of the fact directions are in the generated CONTRIBUTING.md

**Comment by satya164** [comment]
> Thanks. Might want to make some mention of this in this repos readme, or at least some mention of the fact directions are in the generated CONTRIBUTING.md

CONTRIBUTING.md is mentioned in your repo's README, as well as after generating the project.
