### ISSUE TITLE
Automatic inclusion of `package.json` breaks Next SSG

### ISSUE THREAD

**Issue by tjzel** [callstack/react-native-builder-bob#625]
### Description

After bumping `react-native-builder-bob` in Reanimated monorepo, our [example app using Next](https://github.com/software-mansion/react-native-reanimated/tree/main/apps/next-example) stopped building with a very obscure error.

<details>
<summary> Errors screenshots </summary>

![Screenshot 2024-09-08 at 13 21 12](https://github.com/user-attachments/assets/3d1dedb7-9f67-4ef1-8b69-fffe52fe6197)

![Screenshot 2024-09-08 at 13 19 44](https://github.com/user-attachments/assets/750de766-a835-476d-97a5-6c19019f77a8)

</details>

Obviously this file doesn't have any instances of `global` and it worked well before the bump.

After investigation turns out the culprit is enforced addition of `package.json` into the build directory added in

- #598

I don't exactly understand why is that causing the error, especially that the error message and the callstack itself don't provide any useful information.

### Packages

- [ ] create-react-native-library
- [X] react-native-builder-bob

### Selected options

```json
 {    "source": "src",
    "output": "lib",
    "targets": [
      "module",
      "typescript"
    ]
  }
```

### Link to repro

https://github.com/software-mansion/react-native-reanimated/tree/main/apps/next-example

### Environment

Irrelevant, since it [breaks in GitHub actions as well](https://github.com/software-mansion/react-native-reanimated/actions/runs/10759050875/job/29835259916).

**Comment by tjzel** [comment]
Hey @satya164, thanks for the quick release! I tested it and unfortunately the inclusion of `package.json` with `"type":"commonjs"` still breaks Next 😢 

![Screenshot 2024-09-08 at 15 45 08](https://github.com/user-attachments/assets/ee5d140a-57dd-46cb-a264-7817cf6c9bdd)

Also, using the following config:

```json
{
    "source": "src",
    "output": "lib",
    "targets": [
      [
        "module",
        {
          "esm": true
        }
      ],
      "typescript"
    ]
}
```

results in the same error as in the original issue.

**Comment by satya164** [comment]
@tjzel seems like this is a NextJS bug :<
`type: commonjs` should behave exactly like having no `type`. without this there is no way to support specifying `type: module` in root `package.json`. we can temporarily remove the `package.json` but it's not a permanent solution.

**Comment by satya164** [comment]
> results in the same error as in the original issue.

When ESM option is enabled, afaik it's necessary to use `globalThis` instead of `global` since `global` is a legacy thing.

**Comment by satya164** [comment]
Hey @tjzel, there was a mistake in my change - the `package.json` should be emitted when `esm: true` but it did the opposite. I have fixed this issue - so for reanimated you may want to set `esm: false` instead when you upgrade since you don't want the `package.json` to be generated.

**Comment by tjzel** [comment]
@satya164 Sorry for the late response, thanks for pinging!

Unfortunately we cannot upgrade to the latest version of Bob, because we had to strip `@babel/preset-react` https://github.com/software-mansion/react-native-reanimated/pull/7266 to preserve JSX.

I tried to upstream this change as a configuration specific thing, but couldn't get it to work properly so I left is as a patch 😢 Is it something you could do on your end?

**Comment by satya164** [comment]
@tjzel i'm not sure about making this change in bob as not pre-compiling JSX defeats one of the goals - to avoid additional setup for users. imo nativewind should really figure out another way instead of requiring library authors to ship uncompiled code.

but if you want to have this i'd suggest to have your own babel config instead of patching https://callstack.github.io/react-native-builder-bob/build#configfile. then you could do something like:

```js
const bobPreset = require('react-native-builder-bob/babel-preset');

module.exports = {
  ...bobPreset,
  presets: bobPreset.presets.filter(...) // filter out `@babel/preset-react`
};
```

**Comment by tjzel** [comment]
I'll check if this works then!

**Comment by tjzel** [comment]
With a bit of fiddling your suggestion worked when I removed the patch - I got the same exact output. However, when I upgraded bob to the latest version, I'm getting an error:

```console
$ yarn bob build
bob build

build files for publishing

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --target   The target to build
               [string] [choices: "commonjs", "module", "typescript", "codegen"]

Error: Invalid configuration in /Users/bigpoppe/swmansion/reanimated/ternary/packages/react-native-worklets/bob.config.js: targets[0][1].configFile must be boolean (was "/Users/bigpoppe/swmansion/reanimated/ternary/bob.babel.config.js") or targets[0] must be exactly length 1 (was 2)
    at Object.build [as handler] (/Users/bigpoppe/swmansion/reanimated/ternary/node_modules/react-native-builder-bob/lib/build.js:38:11)
```

I guess it's a bug since the docs says that `.configFile` can be a string.

**Comment by satya164** [comment]
@tjzel damn, seems the validation is not complete. will fix, but you can just pass `true` and it'll use `babel.config.js`.

**Comment by satya164** [comment]
@tjzel fixed and released

**Comment by tjzel** [comment]
@satya164 thanks, but there are more issues now 😅

Bob works, but it outputs some TypeScript files into `module/` dir, alongside .js ones:

```console
$ git status                        
On branch @tjzel/bump-builder-bob
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        packages/react-native-reanimated/lib/module/ReanimatedModule/NativeReanimated.ts
        packages/react-native-reanimated/lib/module/createAnimatedComponent/NativeEventsManager.ts
        packages/react-native-reanimated/lib/module/specs/NativeReaWorkletsModule.ts
        packages/react-native-reanimated/lib/module/specs/NativeReanimatedModule.ts
        packages/react-native-reanimated/lib/module/specs/ReanimatedNativeComponent.ts
        packages/react-native-worklets/lib/module/WorkletsModule/NativeWorklets.ts
        packages/react-native-worklets/lib/module/specs/NativeWorkletsModule.ts

nothing added to commit but untracked files present (use "git add" to track)
```

<img width="573" alt="Image" src="https://github.com/user-attachments/assets/b6317115-8114-492b-82eb-a14bec7a0cd8" />

You can reproduce that on my branch on Reanimated repo, doing `yarn` and then `yarn workspace react-native-reanimated build`.

**Comment by satya164** [comment]
@tjzel ah that happens because of the filename matches codegen spec file regex and those files need to stay untranspiled. but we have false positives here. i'll add more checks to account for it and let you know. thanks for reporting.

**Comment by satya164** [comment]
@tjzel i have published a new version with additional checks. lemme know if you're still facing any issues
