### ISSUE TITLE
 Releasing lock on daemon addresses registry - windows only

### ISSUE THREAD

**Issue by Alexufo** [callstack/react-native-builder-bob#652]
### Description

Run `npx create-react-native-library@latest awesome-library`
 

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

 What is the name of the npm package? ... react-native-awesome-library
√ What is the description for the package? ... test
√ What is the name of package author? ... test
√ What is the email address for the package author? ... test@example.com
√ What is the URL for the package author? ... http://
√ What is the URL for the repository? ... http://
√ What type of library do you want to develop? » Native module
√ Which languages do you want to use? » Kotlin & Objective-C
√ What type of example app do you want to create? » Test app
✔ Project created successfully at awesome-library!

After `yarn` inside awesome-library and `yarn example android`

Nothing will compiled.

After that I moved to awesome-library\example\android and run `gradle build --debug` and get 
![image](https://github.com/user-attachments/assets/60f72016-8ed7-4801-9045-dab99a6b0031)

And the process is endless

### Link to repro

default project

### Environment
Android Studio Ladybug | 2024.2.1 Patch 1
windows 10*
java 21, java 16

----
*On mac OS works fine

**Comment by atlj** [comment]
Hey, sorry if this sounds wild, but could you try to reboot the computer, remove the `android/.gradle` folder and build again? Seems like this is an issue about globbing within the React Native Community CLI. I couldn't find a GitHub discussion but there was a discussion about this in the React Contributors Discord channel.

cc: @cortinico

**Comment by Alexufo** [comment]
@atlj  thank you. I Reboot pc and clean all java and gradle deps but stil the same issue. 

I can reproduce it on `react-native-test-app`
https://github.com/microsoft/react-native-test-app/issues/2285

**Comment by tido64** [comment]
Not quite sure what's going on but it looks like you're using JVM 11? Can you please try again with 17? And maybe try Temurin as well. I don't have any experiences with Corretto so I don't know if it's compatible or not.

**Comment by tido64** [comment]
I just recalled that we hit a similar issue when bumping to 0.75 which forced us to disable the Windows CI. Anyway, I re-enabled it now and getting hangs similar to what you're experiencing. I added logs in a bunch of places like below:

![Image](https://github.com/user-attachments/assets/84f1e05e-e892-4255-8f79-0ca06ec67edb)

And it looks like it stops at `native_modules.gradle`, which is a script in `@react-native-community/cli-platform-android`:

![Image](https://github.com/user-attachments/assets/64bcf0d0-ec11-434c-9a0b-c006ad5d9b99)

It doesn't look like it's an RNTA issue, but I need to investigate further (i.e. add more logs).

**Comment by tido64** [comment]
I didn't manage to get to the bottom of the issue, but I did find a workaround. If you bump RNTA to [3.10.18](https://github.com/microsoft/react-native-test-app/releases/tag/3.10.18), you should be able to get past this. Let me know how it goes.

**Comment by Alexufo** [comment]
@tido64  thanks. It works now
