### ISSUE TITLE
error Invalid Version: latest

### ISSUE THREAD

**Issue by liujigang** [callstack/react-native-builder-bob#660]
### Description

/Users/user/.npm/_npx/7655a6858458ff34/node_modules/create-react-native-library/lib/utils/spawn.js:27
        reject(new Error(stderr.trim()));
               ^

Error: error Invalid Version: latest.
    at ChildProcess.<anonymous> (/Users/user/.npm/_npx/7655a6858458ff34/node_modules/create-react-native-library/lib/utils/spawn.js:27:16)
    at Object.onceWrapper (node:events:632:26)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)

Node.js v18.20.4

### Packages

- [X] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

❯ npx create-react-native-library@latest react-native-awesome-library
❯ Native module -> Kotlin & Objective-C -> Vanilla

❯ create-react-native-library@0.42.0

### Link to repro

no

### Environment

❯ Node.js v18.20.4
❯ npx --version
❯ 10.7.0
❯ Mac 15.0.1

**Comment by pixalynx** [comment]
I am having the same issue as well doing C++ turbo module vanilla

**Comment by pixalynx** [comment]
I think there is a problem in the latest version, if I run this command (which uses the prev release) it works

`npx create-react-native-library@0.41.2 awesome-library`

**Comment by Garthguo** [comment]
I am having the same issue

**Comment by verger-guo** [comment]
This is help for me https://stackoverflow.com/questions/79073524/react-native-library-command-not-creating-library

**Comment by atlj** [comment]
Hey folks we've published `create-react-native-library@0.44.0` just recently. Could you try again and let me know? Closing the issue for now, please ping me if you still have the same problem.

**Comment by tamdvyounetgroup** [comment]
it was not working

**Comment by AriesHaw** [comment]
> it was not working

change npm registry to https://registry.npmmirror.com/ and try again, its work for me

**Comment by maomaoispan** [comment]
> This is help for me https://stackoverflow.com/questions/79073524/react-native-library-command-not-creating-library

It is work for me to add '--reactNativeVersion 0.77.0' params.

`npx create-react-native-library@latest libname --reactNativeVersion 0.77.0`

**Comment by mobinni** [comment]
Having the same issue downgrading to 0.77 fixes it cc @satya164

**Comment by satya164** [comment]
You can try clearing npx cache, e.g. `npx clear-npx-cache`
