### ISSUE TITLE
Build tool fails for Native Module (unknown option '--npm')

### ISSUE THREAD

**Issue by objectiveSee** [callstack/react-native-builder-bob#663]
### Description

✔ What is the description for the package? … sd
✔ What is the name of package author? … John Doe
✔ What is the email address for the package author? … john.doe@example.com
✔ What is the URL for the package author? … https://github.com/dummyUser
✔ What is the URL for the repository? … https://github.com/dummyUser/demo-rn-bob
✔ What type of library do you want to develop? › Turbo module with backward compat
✖ Which languages do you want to use? › Kotlin & Objective-C
🤖 > npx create-react-native-library@latest demo-rn-bob
(node:41543) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ What is the name of the npm package? … react-native-demo-rn-bob
✔ What is the description for the package? … asd
✔ What is the name of package author? … John Doe
✔ What is the email address for the package author? … john.doe@example.com
✔ What is the URL for the package author? … https://github.com/dummyUser
✔ What is the URL for the repository? … https://github.com/dummyUser/react-native-demo-rn-bob
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Swift
✔ What type of example app do you want to create? › Vanilla
⠏ Generating example app

error: unknown option '--npm'
(Did you mean --pm?)
/Users/johndoe/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/spawn.js:27
        reject(new Error(stderr.trim()));
               ^

Error: error: unknown option '--npm'
(Did you mean --pm?)
    at ChildProcess.<anonymous> (/Users/johndoe/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/spawn.js:27:16)
    at Object.onceWrapper (node:events:635:26)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v22.5.1
🤖 > ```

### Packages

- [X] create-react-native-library
- [X] react-native-builder-bob

### Selected options

✔ What is the description for the package? … sd
✔ What is the name of package author? … John Doe
✔ What is the email address for the package author? … john.doe@example.com
✔ What is the URL for the package author? … https://github.com/dummyUser
✔ What is the URL for the repository? … https://github.com/dummyUser/demo-rn-bob
✔ What type of library do you want to develop? › Turbo module with backward compat
✖ Which languages do you want to use? › Kotlin & Objective-C
🤖 > npx create-react-native-library@latest demo-rn-bob
(node:41543) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
✔ What is the name of the npm package? … react-native-demo-rn-bob
✔ What is the description for the package? … asd
✔ What is the name of package author? … John Doe
✔ What is the email address for the package author? … john.doe@example.com
✔ What is the URL for the package author? … https://github.com/dummyUser
✔ What is the URL for the repository? … https://github.com/dummyUser/react-native-demo-rn-bob
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Swift
✔ What type of example app do you want to create? › Vanilla
⠏ Generating example app

error: unknown option '--npm'
(Did you mean --pm?)
/Users/johndoe/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/spawn.js:27
        reject(new Error(stderr.trim()));
               ^

Error: error: unknown option '--npm'
(Did you mean --pm?)
    at ChildProcess.<anonymous> (/Users/johndoe/.npm/_npx/e106e660d51959d2/node_modules/create-react-native-library/lib/utils/spawn.js:27:16)
    at Object.onceWrapper (node:events:635:26)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)

Node.js v22.5.1
🤖 > ```

### Link to repro

NONE

### Environment

NONE

**Comment by joepatosh** [comment]
I just ran into this same problem.

It seems to specifically happen with the "Vanilla" option - "Test app" seems to work.

this worked:

```
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Swift
✔ What type of example app do you want to create? › Test app
```

this did not:

```
✔ What type of library do you want to develop? › Native module
✔ Which languages do you want to use? › Kotlin & Swift
✔ What type of example app do you want to create? › Vanilla
```

Reproduced on both [0.42.0](https://github.com/callstack/react-native-builder-bob/releases/tag/create-react-native-library%400.42.0) and [0.41.2](https://github.com/callstack/react-native-builder-bob/releases/tag/create-react-native-library%400.41.2)
