### ISSUE TITLE
Error: @react-native/metro-config@npm:0.76.1: No candidates found

### ISSUE THREAD

**Issue by l2hyunwoo** [callstack/react-native-builder-bob#673]
### Description

When I install dependencies using yarn, it fails due to error as referred on title.

```shell
$ yarn
➤ YN0000: ┌ Resolution step
// Remove other logs
➤ YN0001: │ Error: @react-native/metro-config@npm:0.76.1: No candidates found
    at ge (/Users/l2hyunwoo/.cache/node/corepack/v1/yarn/3.6.1/yarn.js:439:8124)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 7)
    at async io (/Users/l2hyunwoo/.cache/node/corepack/v1/yarn/3.6.1/yarn.js:390:10398)
➤ YN0000: └ Completed in 45s 170ms
➤ YN0000: Failed with errors in 45s 172ms
```

### Packages

- [x] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

![Image](https://github.com/user-attachments/assets/cb5f4304-760c-445a-bf91-ef1355964983)

### Link to repro

https://github.com/l2hyunwoo/react-native-bob-error-repro

### Environment

System:
  OS: macOS 14.6.1
  CPU: (16) arm64 Apple M3 Max
  Memory: 678.23 MB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.20.3
    path: ~/.nvm/versions/node/v18.20.3/bin/node
  Yarn:
    version: 4.0.2
    path: ~/.nvm/versions/node/v18.20.3/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v18.20.3/bin/npm
  Watchman:
    version: 2024.10.28.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.16.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "33"
      - "34"
      - "35"
    Build Tools:
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | ARM 64 v8a
      - android-34 | Google APIs ARM 64 v8a
      - android-35 | Google APIs ARM 64 v8a
      - android-35 | Google Play ARM 64 v8a
    Android NDK: Not Found

**Comment by atlj** [comment]
Hey could you try it again? I think this might've been a temporary network issue on your end. And it looks like [@react-native/metro-config@0.76.1](https://www.npmjs.com/package/@react-native/metro-config/v/0.76.1) was already published. Closing the issue, please let me know if you still have this problem.
