### ISSUE TITLE
Unable to create new projects with vanilla example apps targeting react-native < 0.76

### ISSUE THREAD

**Issue by jonthysell** [callstack/react-native-builder-bob#674]
### Description

When calling `create-react-native-library` and specifying a `react-native` version < 0.76, we hit the new assert: `The generated example app doesn't have community CLI installed`

This is because neither the `@react-native-community/template` for 0.75 nor the `react-native` template for 0.74 have the CLI specified as a direct dependency.

### Packages

- [x] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

npx --yes create-react-native-library@latest --slug testcli --description testcli --author-name "React-Native-Windows Bot" --author-email 53619745+rnbot@users.noreply.github.com --author-url http://example.com/ --repo-url http://example.com/ --languages kotlin-objc --type module-new --react-native-version 0.75.3 --example vanilla testcli

### Link to repro

https://github.com/microsoft/react-native-windows

### Environment

info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.26100
  CPU: "(24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores     "
  Memory: 50.03 GB / 63.86 GB
Binaries:
  Node:
    version: 18.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.22
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.8.1
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.12.35309.182 (Visual Studio Enterprise 2022)
    - 17.11.35327.3 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: 0.75.3
  react-native-windows:
    installed: 0.75.7
    wanted: 0.75.7
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

**Comment by satya164** [comment]
The `--react-native-version` is meant for debugging purposes as well as testing upcoming versions of React Native. Officially, `create-react-native-library` only supports the current stable version of React Native when generating the project as it's a massive task to add custom logic for changes in the template for every version.

So if you need to use a previous version of React Native, I'd recommend hardcoding to the last known working version of `create-react-native-library` instead of `latest`.
