### ISSUE TITLE
Cannot run the expo example project after create project

### ISSUE THREAD

**Issue by AnnaClaudiaSacute** [callstack/react-native-builder-bob#682]
### Description

I can not run the expo example project after create the project after configure the lib.

Steps to reproduce:

1. Run the command like the documentation: `npx create-react-native-library@latest awesome-library`
2. Fill the questions
3. After the project is created, go project folder and run npm install
4. After install dependencies got to example project with `cd example`
5. Run `npm start`
6. Open app in Expo Go and you will se the error bellow

![Image](https://github.com/user-attachments/assets/384bf093-14ca-42ba-80ae-500fa28d89c9)

PS: I have tried with versions 0.41.0, 0.42.0 and 0.43.0 from `create-react-native-library`.

### Packages

- [x] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

✔ What is the name of the npm package? … awesome-library
✔ What is the description for the package? … anna-components
✔ What is the name of package author? … Anna
✔ What is the email address for the package author? … ana@gmail.com
✔ What is the URL for the package author? … https://github.com/ana4
✔ What is the URL for the repository? … https://github.com/ana4/awesome-library
✔ What type of library do you want to develop? › JavaScript library

### Link to repro

Dont have a repo

### Environment

Node version 20.0
MacOS: 12.7.6
create-react-native-library:  0.43.0

**Comment by AnnaClaudiaSacute** [comment]
PS: I have tried with versions 0.41.0, 0.42.0 and 0.43.0 from `create-react-native-library`.

**Comment by atlj** [comment]
Looks like we have something similar on CI https://github.com/callstack/react-native-builder-bob/actions/runs/11862708471/job/33062684713?pr=685

👀
