### ISSUE TITLE
Add template for React Native Windows plugins

### ISSUE THREAD

**Issue by hassankhan** [callstack/react-native-builder-bob#69]
# Feature request

It would be nice to have a plugin template for [React Native Windows](https://github.com/microsoft/react-native-windows). Perhaps someone from Microsoft (@stmoy?) might be able to help out?

## Why it is needed

Adding a template for RN Windows will help potential contributors follow a "best-practice" way of adding support for Windows to their desired plugins

## Possible implementation

Windows projects use Visual Studio solution files (`*.sln`). The following repositories have Windows support:

- [`react-native-webview`](https://github.com/react-native-community/react-native-webview)
- [`async-storage`](https://github.com/react-native-community/async-storage)
- [`react-native-netinfo`](https://github.com/react-native-community/react-native-netinfo)

**Comment by stmoy** [comment]
This would be a great thing to support! We have an issue on our backlog (linked above). We currently don't have the funding to add this support, but it's definitely something that has come up before.

**Comment by satya164** [comment]
Currently there are no plans to add Windows support as it adds additional maintenance cost. Happy to revisit in the future if someone wants to maintain this feature.
