### ISSUE TITLE
Getting "Execution failed for task ':app:invokeLibraryCodegen'" when running yarn android inside Fabric View Library

### ISSUE THREAD

**Issue by hamdoudhakem** [callstack/react-native-builder-bob#699]
### Description

I started a new Blank Library using the `Fabric View` template, after I ran `yarn install` in the project root and inside the example folder without changing or doing anything else I ran `yarn android` and I keep getting this error:
![Image](https://github.com/user-attachments/assets/89a42058-4daa-4baa-98e0-fa5703161235)

I also tried the `Fabric View with backward compatibility` template and I got the same error.
I also followed these docs to check if anything was wrong with the template and I didn't find anything: https://github.com/reactwg/react-native-new-architecture/blob/main/docs/fabric-native-components.md

### Packages

- [x] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

Fabric View

### Link to repro

https://github.com/hamdoudhakem/react-native-chat-llm

### Environment

- System:
  - OS: Windows 11 10.0.22631
  - CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  - Memory: 1.73 GB / 15.78 GB
- Binaries:
  - Node:
    - version: 20.18.0
    - path: C:\Program Files\nodejs\node.EXE
  - Yarn:
    - version: 3.6.1
    - path: ~\AppData\Roaming\npm\yarn.CMD
  - npm:
    - version: 10.9.0
    - path: C:\Program Files\nodejs\npm.CMD
  - Watchman: Not Found
- SDKs:
  - Android SDK: Not Found
  - Windows SDK: Not Found
- IDEs:
  - Android Studio: AI-242.21829.142.2421.12409432
  - Visual Studio:
  - 17.11.35327.3 (Visual Studio Community 2022)
- Languages:
  - Java: 17.0.13
  - Ruby: Not Found
- npmPackages:
  - "@react-native-community/cli":
    - installed: 15.0.1
    - wanted: 15.0.1
  - react:
    - installed: 18.3.1
    - wanted: 18.3.1
  - react-native:
    - installed: 0.76.3
    - wanted: 0.76.3
  - react-native-windows: Not Found
- npmGlobalPackages:
  - "*react-native*": Not Found
- Android:
  - hermesEnabled: true
  - newArchEnabled: true
- iOS:
  - hermesEnabled: Not found
  - newArchEnabled: Not found

**Comment by antoine1anthony** [comment]
Hey, just a thought have you tried downgrading your node version from 20 to 18.

**Comment by ddiazFG** [comment]
Same here, I modified a little bit the commandLine, I created a [PR](https://github.com/callstack/react-native-builder-bob/pull/707), let me know if it is an ok solution, thanks.:

```gradle
if (isNewArchitectureEnabled()) {
    // Since our library doesn't invoke codegen automatically we need to do it here.
    tasks.register('invokeLibraryCodegen', Exec) {
        workingDir "$rootDir/../../"

        def isWindows = System.getProperty('os.name').toLowerCase().contains('windows')

        if (isWindows) {
            commandLine 'cmd', '/c', 'npx bob build --target codegen'
        } else {
            commandLine 'sh', '-c', 'npx bob build --target codegen'
        }

        doFirst {
            println "Running on OS: ${System.getProperty('os.name')}"
            println "Working Directory: ${workingDir.absolutePath}"
        }
    }
    preBuild.dependsOn invokeLibraryCodegen
}
```

info about my environment:

nvm.
node 18.

**Comment by satya164** [comment]
Closing since the PR is merged
