### ISSUE TITLE
Add template for React Native macOS plugins

### ISSUE THREAD

**Issue by hassankhan** [callstack/react-native-builder-bob#70]
# Feature request

It would be nice to have a plugin template for [React Native macOS](https://github.com/microsoft/react-native-macos). Perhaps someone from Microsoft (@stmoy?) might be able to help out?

## Why it is needed

Adding a template for RN macOS will help potential contributors follow a "best-practice" way of adding support for macOS to their desired plugins.

## Possible implementation

macOS projects are similar to iOS projects, in that they both use Xcode (`*.pbxproj`). The following repositories have macOS support:

- [`react-native-webview`](https://github.com/react-native-community/react-native-webview)
- [`async-storage`](https://github.com/react-native-community/async-storage)
- [`react-native-netinfo`](https://github.com/react-native-community/react-native-netinfo)

**Comment by satya164** [comment]
Currently there are no plans to add MacOS support as it adds additional maintenance cost. Happy to revisit in the future if someone wants to maintain this feature.
