### ISSUE TITLE
Expo example yields "Unable to resolve module ./.expo/.virtual-metro-entry"

### ISSUE THREAD

**Issue by kraenhansen** [callstack/react-native-builder-bob#722]
### Description

Instantiating a library with an expo example leads to the following error when starting app and loading the bundle via the Metro dev-server:

> Unable to resolve module ./.expo/.virtual-metro-entry from (...)
![Image](https://github.com/user-attachments/assets/e7ff62f4-0956-47d1-af19-d6a3ae3021e8)

Searching ☝ lead me to https://github.com/react-native-community/upgrade-support/issues/248#issuecomment-2002598101

I believe the root cause is this file [templates/example-common/example/metro.config.js](https://github.com/callstack/react-native-builder-bob/blob/9c5638a224d558071ae01f010da8b7a6860f00ee/packages/create-react-native-library/templates/example-common/example/metro.config.js#L2) overrides this file [templates/expo-library/example/metro.config.js](https://github.com/callstack/react-native-builder-bob/blob/9c5638a224d558071ae01f010da8b7a6860f00ee/packages/create-react-native-library/templates/expo-library/example/metro.config.js).

### Packages

- [x] create-react-native-library
- [ ] react-native-builder-bob

### Selected options

I ran

```
npx create-react-native-library@latest react-native-automerge --type turbo-module --example expo --languages cpp
```

### Link to repro

N/A

### Environment

```
System:
  OS: macOS 14.7.1
  CPU: (14) arm64 Apple M3 Max
  Memory: 485.92 MB / 36.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.11.0
    path: ~/.local/state/fnm_multishells/57541_1733576637502/bin/node
  Yarn: Not Found
  npm:
    version: 10.9.0
    path: ~/.local/state/fnm_multishells/57541_1733576637502/bin/npm
  Watchman:
    version: 2024.11.11.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.4
      - iOS 17.4
      - macOS 14.4
      - tvOS 17.4
      - visionOS 1.1
      - watchOS 10.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.2 AI-232.10300.40.2321.11567975
  Xcode:
    version: 15.3/15E204a
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.13
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 16.0.0
    wanted: ^16.0.0
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

**Comment by satya164** [comment]
Currently expo example is only supported for JS-only modules. So this is not a valid combination.
