### ISSUE TITLE
Java instead of Kotlin

### ISSUE THREAD

**Issue by utarit** [callstack/react-native-builder-bob#82]
Hi, is it possible that I use java instead of kotlin on Android side? If possible how can I do it? 

Thanks in advance

**Comment by NeliHarbuzava** [comment]
Any info?

**Comment by Krizzu** [comment]
You can open the project in Android Studio and select `Menu > Tools > Kotlin -> Decompile Kotlin to Java` to get Java instead of Kotlin

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/93548570-0d33cd80-f99a-11ea-9280-5190062e7f48.png)
``Menu > Tools > Kotlin -> Decompile Kotlin to Java`` Can not be selected

**Comment by Krizzu** [comment]
That works only for compiled kt classes (`app/build/tmp/kotlin-classes/`). Other than that, you can select `Tools -> Kotlin -> Show Kotlin Bytecode` and in the new window `Decompile` to get the same result (Java code).

**Comment by aprilmintacpineda** [comment]
I think this should be an option,

- Java and Swift
- Java and Objective-C

**Comment by mtzfactory** [comment]
Yeah, would be nice to have the option to include the option to create a library in Java for Android...
